### ISSUE TITLE
Convert the Meetup Assets page 

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#10]
## Goal
The goal of this issue is to recreate the Meetup Assets page https://emberjs.com/meetup-assets/  in an Ember app. The currently deployed site is a Ruby app found [in a different repository](https://github.com/emberjs/website), and we are working towards converting the whole site over.

## Criteria
- [ ] Add route: `/community/meetups/assets`
- [ ] The content look should be the same as the live site
- [ ] use ember-styleguide components (and make notes where there is not an appropriate component)
- [ ] remove the top level `meetup-assets` route
- [ ] ensure that the project builds and all tests pass

## Additional Info
- To get started with this issue, please add a comment that you are interested in helping out with it. 
- If you have questions, need to get someone's attention for feedback, or it's your first time contributing, the learning team can help you out! The best way to get in touch is to join the [Ember Community Discord](https://discord.gg/emberjs) and join the #dev-ember-learning channel. Thank you!

**Comment by claeusdev** [comment]
Hi @mansona I'll take a look at this.

**Comment by mansona** [comment]
Hey @claeusdev 👋 did you have a chance to take a look at this? 

Let me know if you have any questions or need any assistance 👍

**Comment by claeusdev** [comment]
Hey @mansona, I am currently looking at it. I'll be sure to let you know how it's going
