### ISSUE TITLE
Error of syntax ?

### ISSUE THREAD

**Issue by Alicexplore** [ember-learn/ember-website#1064]
don't we have to delete "div class="jumbo" too ?

<img width="839" alt="Capture d’écran 2023-10-02 à 13 51 55" src="https://github.com/ember-learn/ember-website/assets/102388803/d993d1a5-ac05-4484-9dc4-6b0eda4df2d0">

**Comment by MinThaMie** [comment]
Our highlighter was broken a bit, and now fixed so this is no longer an issue :)
