### ISSUE TITLE
Clarification of Ember 5.8 LTS Status

### ISSUE THREAD

**Issue by captn3m0** [ember-learn/ember-website#1103]
Filing this on behalf of endoflife.date, where I was trying to [update the dates for 5.8 release](https://github.com/endoflife-date/endoflife.date/pull/5021), and had some questions.

[/lts](https://emberjs.com/releases/lts/) marks the dates for 5.8 as:

Event|Date
---|---
LTS Promotion|April 15, 2024
Bug Fixes Until|November 11, 2024
Security Fixes Until|April 28, 2025

With the following caveats:

>  Before a version can be called an "LTS" release, it has to spend at least 6 weeks as a stable release, where it is used and tested by thousands of developers. 

> Once a release of Ember gets promoted to LTS, it receives bugfixes for 36 weeks and security updates for 54 weeks. 

The dates mentioned in #1102 do not align with the policy:

- 5.8.0 was [tagged on 15th April 2024](https://github.com/emberjs/ember.js/releases/tag/v5.8.0) with the official announcement made on [20th April 2024](https://blog.emberjs.com/ember-released-5-8). It says:
  > **Today** the Ember project is releasing version 5.8 of Ember.js and Ember CLI. This release of Ember.js is an LTS (Long Term Support) candidate.
- The expected date for LTS Promotion should be 1st June (2024-04-20 +6w), which does not match the date used in #1102
- The published date for Bug Fixes does not match the policy (2024-11-11'-36 weeks' = 2024-03-04). Expected Date as per the policy would be (2024-12-28)

## Open Questions:

1. Is 5.8 a LTS candidate or promoted to LTS already? Is there a reason for the "6 weeks as stable" part being ignored?
2. What is the official release date for 5.8, used in the policy - the date of the git tag, or the announcement blog post?
3. In case the published dates override the policy, perhaps the policy can be updated to include such a note?

Apologies if this sounds like hair-splitting, but I wanted to make sure we have the right dates.

**Comment by kategengler** [comment]
Hi! We've since made updates to [/lts](https://emberjs.com/releases/lts/) and the dates should be more explicit and correct.

LTSes are a candidate for 6 weeks after their release (or sometimes longer if we feel it isn't ready for promotion to LTS). We now track the promotion date on the LTS page. 

The official release date for a version of Ember.js is the announcement blog post. We have several packages that need to be released for each "release" of Ember.

**Comment by captn3m0** [comment]
The updates are helpful, and tracking the promotion dates as explicit makes it much better.
