### ISSUE TITLE
Add unadorned mascots to top of Mascots page

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#114]
We received the feedback that it was hard to find the unadorned versions of the masccots in the website.
Following #17, an unadorned Tomster and Zoey pair should be added to the top of the page, below the "Tomster and Zoey" header.

**Comment by jwithington** [comment]
Hey folks! I'm starting to work on this, and I found an unadorned Zoey here (after running a build):

`dist/images/tomsters/zoey.png`

However, I'm actually not seeing any plain Tomsters (that aren't just a head, an Ember logo, etc.). This is the one marked as original:

`dist/images/tomsters/original.png`
 
Do you know where I might look, or is that the right one to use?

Thanks so much!

cc: @locks @MelSumner

**Comment by locks** [comment]
Before building the mascot images are at `/public/images/tomsters`.
That's a good question, I don't remember seeing an unadorned Tomster! I've asked @wifelette for confirmation.

**Comment by jwithington** [comment]
Great — I can grab anything she provides and include them, too. ☺️

**Comment by MelSumner** [comment]
@wifelette where is the original Tomster?
