### ISSUE TITLE
Change the /tomster route to /mascots

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#115]
The /tomster/ route was already being redirected- the Ember version of the website should go ahead and use the /mascots/ route instead. 

To-Do:
- [ ] update the route name for /tomster/ to /mascots/
- [ ] update the subroutes
- [ ] update any tests
- [ ] ensure all tests pass and the project builds successfully

**Comment by locks** [comment]
We need to redirect `/tomster/*`.

**Comment by BradLeftley** [comment]
Hey I can pick this up 👍

**Comment by locks** [comment]
@BradLeftley sounds good, thanks! Let us know here or on Discord if you have any problems.

**Comment by MelSumner** [comment]
@BradLeftley is there anything I can help with to move this over the finish line?

**Comment by locks** [comment]
Thanks!
