### ISSUE TITLE
add statusboard page

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#117]
Currently, the statusboard is located in a separate app. Now that the entire site will be in Ember, we can eliminate this bifurcation by moving the statusboard content to this repo. 

## To Do
- [ ] ensure that the correct route exists
- [ ] Use the es-accordion component from [ember-styleguide](https://github.com/ember-learn/ember-styleguide) to implement the accordion found on [the statusboard page](https://emberjs.com/statusboard/)
- [ ] put the data for the page in json format for now- we're still figuring out the best way to track overall projects.

**Comment by claeusdev** [comment]
@MelSumner @mansona This looks like my next PR. I'm taking this on

**Comment by mansona** [comment]
Sorry @claeusdev 🙈 this was actually done in #154 I must have missed this issue
