### ISSUE TITLE
New Feature: Project Showcase

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#118]
We'd like to add a new feature to the website that showcases 3-4 projects using Ember. We intend to cycle these on a regular basis. 

- [ ] add showcase as a child route to community
- [ ] each showcase should then also have it's own child route (https://guides.emberjs.com/release/routing/redirection/#toc_child-routes)
- [ ] use json api to structure the data for the showcase- it should support a thumbnail, a link, a title, a description, and a date added. 
- [ ] front-end presentation should be an unordered list in the HTML (for accessibility purposes)
- [ ] CSS styling should be written in a mobile-first way
- [ ] a screenshot should be included in your PR

Questions? Visit the dev-ember-learning channel in [Ember Discord](https://discord.gg/emberjs) chat.

**Comment by claeusdev** [comment]
@MelSumner I am working on this .

**Comment by MelSumner** [comment]
@claeusdev let me know if you'd like someone to pair with, or if you want a code review! Thank you for your help!

**Comment by jwithington** [comment]
I'm curious about this one -- I'm interested in tackling it if it's still open / help is still needed.

Thanks! cc: @MelSumner

**Comment by mansona** [comment]
@jwithington the current blocker for this work is that we need to start getting some content together that will be able to drive the design/functionality of the showcase section. We have talked about putting together some sort of "submit your own whitepaper" documentation that would feed into this section of the website but we haven't had much of a chance to move that forward 🤔 

If you are interested in helping to progress this issue I would recommend joining the discussion in #dev-ember-learning on Discord (or we can continue it here if you prefer). Also, even better than participating by text, we have an open weekly meeting on Thursdays that anyone can join in on 👍

**Comment by jwithington** [comment]
great, thanks!
