### ISSUE TITLE
Move deprecations from separate app into the main site

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#119]
## Goal 
Consolidate https://github.com/ember-learn/deprecation-app into this app. 

## To Do
- [ ] add the deprecations route as a child route to releases
- [ ] add ember-data, ember-cli and ember as child routes to deprecations
- [ ] each major version should have its own child route within the relevant project
- [ ] move over [deprecation content](https://github.com/ember-learn/deprecation-app/tree/master/content)

**Comment by paxer** [comment]
Hi folks, I would like to help with this issue but I am relatively new to Ember community so pls expect many questions along the way :)

The first question - as I understood we need to move all content form this app https://github.com/ember-learn/deprecation-app to the new Ember site which is this repo (ember-website) right?

The first task is to add `deprecations` route as a child route to `releases` route as I understand? But when I check https://github.com/ember-learn/ember-website/blob/master/app/router.js - there is no  `releases` route there yet, should we create it as well or I am missing something?

**Comment by paxer** [comment]
alright I think as with the old (current site) "Releases" is just a menu and should not be a route with URL, just wanted to make sure, but seems like this is what we want to leave in a new site as well

**Comment by paxer** [comment]
A question regarding moving over deprecation content https://github.com/ember-learn/deprecation-app/tree/master/content

the content there is in Markdown format, should we move it as HTML or maybe leave it as Markdown  and use some Markdown to HTML component to render it on the page?

**Comment by mansona** [comment]
Hey @paxer 👋 

Are you on the Ember Community Discord? can you ping me (@real_ate) either directly or in #dev-ember-learning to chat about this issue? 😄

**Comment by paxer** [comment]
Hey @mansona 

I don't use Discord, not a problem to join though, however isn't it a good idea to keep all discussions about the issue in one place so anybody can review history in one place and not forced to jump between chat and GitHub?

**Comment by mansona** [comment]
@paxer yes absolutely, we do tend to keep most of the conversation that is directly related to an issue or PR on GitHub because it's easier for new developers to discover 👍 In this particular case there is a bit of a more nuanced discussion that is going on and I thought you would be interested in having a bit more "real time" discussion 😄 

I'll get back to you with a response here in the next few days 👍

**Comment by mansona** [comment]
Hey @paxer 👋 

Just to let you know that we talked about this issue in our weekly Learning Team meeting (notes available here: https://github.com/emberjs/core-notes/blob/master/docs-team/2019-01/january-10.md#deprecations-app-as-standalone-app-separate-from-the-rest-of-website )

We still haven't quite decided if this is going to go ahead so I would recommend pausing any work that you might be doing on it just in case 👍 Let me know if there is something else that you would like to contribute to on the website, specifically anything on this Project board: https://github.com/orgs/ember-learn/projects/8 (which I'll be updating over the next few days)

**Comment by paxer** [comment]
Hey @mansona 

No probs, what would you recommend for me given my CSS skills are quite depressing, and as I understand we don't currently have CSS styles and HTML templates ready for the new website? Or perhaps moving some parts could be done with the old markup or with some basic HTML structure and apply CSS later?

**Comment by mansona** [comment]
hey @paxer just to let you know we have decided on the way forward for the deprecations app for now. we are **not** going to build it into the main website code but instead we are going to move it into its own subdomain.

You can read more about that decision here: https://github.com/ember-learn/handbook/blob/master/infra_domains.md#sub-domains

Let me know if you have any questions or if you would like to work on something else in the current "Emberification" project: https://github.com/orgs/ember-learn/projects/8
