### ISSUE TITLE
Move /builds to /releases and add more relevant content

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#121]
This is essentially a follow on from https://github.com/ember-learn/ember-website/issues/142 and should likely not be worked on until that issue is finished 👍 

Note: this might turn into more of a meta/tracking issue- it's definitely a bigger chunk of work than typical single issues. 

## Goals
The idea is that the new `/releases` page will replace the current `/builds`, as well as integrate the release blog posts. This in turn will enable the release blog posts to be much more about the why, instead of technical implementation details, aiding in marketing efforts.

## To do
- Include information on:
  - http://emberjs.com/builds/
  - http://emberjs.com/blog/2013/09/06/new-ember-release-process.html
  - http://emberjs.com/blog/2015/06/16/ember-project-at-2-0.html
  - http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html
- Document releases separately from blog

## Features
- current version should be prominent on the page
- widget that will show a yearly calendar in the releases pages, with the releases calculated :x
- release train visual (like current builds)
- description of release process
- list of channels
  - make sure we list all active LTSs

**Comment by mikoscz** [comment]
I'm starting this one 😄

**Comment by mansona** [comment]
hey @mikoscz 👋 how did you get on with looking at this issue? I'm doing a bit of work to better define what the most pressing tasks are for the Ember Website "Emberification" project so let me know if you want to still be involved and help out and I can help you in whatever way you need 👍

**Comment by mansona** [comment]
This is covered in #351
