### ISSUE TITLE
Make sure there is a Netlify redirect from `/about` to the homepage

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#145]
This is something that seems to exist on the existing website and needs to be replicated here. 

Netlify redirects are defined here: https://github.com/ember-learn/ember-website/blob/master/.netlifyredirects

Also make sure to remove the `/about` route from the Ember routes definition

**Comment by patocallaghan** [comment]
I may as well take this one too as it's pretty much the same as https://github.com/ember-learn/ember-website/issues/146

**Comment by mansona** [comment]
yes indeed @patocallaghan 🎉 thanks a million! I'll mark it as in progress
