### ISSUE TITLE
Make sure there is a Netifly redirect from `/documentation` to the Ember Guides

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#147]
This exists on the current ember website and needs to be replicated here :+1:

Netlify redirects are defined here: https://github.com/ember-learn/ember-website/blob/master/.netlifyredirects

This redirect needs to be a [splats](https://www.netlify.com/docs/redirects/#splats) redirect and be the same as the `/guides` redirect that already exists

Also make sure to remove the `/documentation` route from the Ember routes definition

**Comment by patocallaghan** [comment]
I'll take this ✋

**Comment by mansona** [comment]
🎉 thanks @patocallaghan
