### ISSUE TITLE
Implement the Payment Page for Tomster Comissions

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#148]
This issue is to re-implement https://emberjs.com/tomster/payment/ as `/mascots/payment`

Make sure you implement the "payment sent" page too

**WARNING:** this needs to be implemented alongside the core-team. You **must** reach out to the Ember Core Learning team before starting this implementation. We recommend that you ask about this issue in #dev-team-learning in the Ember Community Discord

**Comment by patocallaghan** [comment]
@mansona I'd like to take this 🤚
