### ISSUE TITLE
Move the Legal page to the correct place

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#15]
## Goal
The goal of this issue is to recreate the page https://emberjs.com/legal/ in an Ember app.  The currently deployed site is a Ruby app found [in a different repository](https://github.com/emberjs/website), and we are working towards converting the whole site over.

## Criteria
- [ ] remove /legal as a top-level route
- [ ] re-add route to /about/legal
- [ ] The content look be the same as the current template
- [ ] use ember-styleguide components (and make notes where there is not an appropriate component)

## Additional Info
- To get started with this issue, please add a comment that you are interested in helping out with it. 
- If you have questions, need to get someone's attention for feedback, or it's your first time contributing, the learning team can help you out! The best way to get in touch is to join the [Ember Community Discord](https://discord.gg/emberjs) and join the #dev-ember-learning channel. Thank you!

**Comment by abhilashlr** [comment]
@mansona I can work on this.

**Comment by abhilashlr** [comment]
@mansona should we close this issue since this PR is merged?

**Comment by locks** [comment]
@abhilashlr it is still a top-level route, and not `/about/legal`, confirm?

**Comment by abhilashlr** [comment]
@locks yes. It isn't. But what happens to the current (https://www.emberjs.com) working page `/legal` ? Should it be re-routed to `/about/legal` ?

**Comment by abhilashlr** [comment]
* [x] remove /legal as a top-level route
* [x]  re-add route to /about/legal
* [x]  The content look be the same as the current template
* [x]  use ember-styleguide components (and make notes where there is not an appropriate component)
