### ISSUE TITLE
Make sure the nav bar closes and we scroll to top after navigation

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#151]
This should utilise https://emberjs.com/api/ember/3.7/classes/RouterService/events/routeDidChange?anchor=routeDidChange to close the navbar and scroll to the top of the page

There is a chance that we might need to do this in Ember Styleguide (because of the navbar service) but it might be possible now in the website directly.

Let us know if you want to take this on or if you have any questions :+1:

**Comment by patocallaghan** [comment]
@mansona I can take this one

**Comment by mansona** [comment]
@patocallaghan nice one 🎉 you're a legend

**Comment by mansona** [comment]
@patocallaghan now that https://github.com/ember-learn/ember-styleguide/pull/142 is merged you can update the dependency on styleguide directly since it's a git dependency right now https://github.com/ember-learn/ember-website/blob/master/package.json#L59

thanks again for looking at this 🎉
