### ISSUE TITLE
Navbar dropdown is hidden behind map

### ISSUE THREAD

**Issue by simonihmig** [ember-learn/ember-website#152]
![image](https://user-images.githubusercontent.com/1325249/52701080-aa867e80-2f79-11e9-9810-1f431f328bfd.png)

Proposed solution: `z-index: 1000000` (the more the better 😬)

Seriously though, idk why the leaflet has to use such a high z-index, but that seems to come from the addon's vendor css...

![image](https://user-images.githubusercontent.com/1325249/52701223-03561700-2f7a-11e9-8d97-d6f3028c7526.png)

**Comment by mansona** [comment]
This change is probably best added to https://github.com/ember-learn/ember-styleguide if anyone wants to take this up 👍
