### ISSUE TITLE
Add the community survey banner to the new website

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#171]
You may have noticed the community survey banner on the currently live website :tada: 

As we hope to launch the new website while the community survey is still active we need to re-implement the banner for the site.

You can take a look at this code: https://github.com/ember-learn/guidemaker-ember-template/blob/master/addon/templates/components/ember-survey.hbs (with the corresponding CSS and component file) to see how we do it in an Ember app :+1:

**Comment by patocallaghan** [comment]
✋ I'll take this as a precursor to doing #173

**Comment by mansona** [comment]
thanks @patocallaghan 🎉
