### ISSUE TITLE
Port the previous year's community survey pages

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#172]
We need to port the pages for the previous years' community surveys

https://emberjs.com/ember-community-survey-2016/
https://emberjs.com/ember-community-survey-2017/
https://emberjs.com/ember-community-survey-2018/

Although at first glance it would make sense to convert these into individual subroutes like this: https://emberjs.com/ember-community-survey/2016/ and share the code between them I do **not** want us to do that yet. We can add a task in the [Emberification of the Website phase 2](https://github.com/orgs/ember-learn/projects/13) project to simplify these pages and have them use a shared implementation 👍 

It might make sense to have shared components between these pages but I would recommend just a copy and paste job in the interest of speed 👍

**Comment by aklkv** [comment]
@mansona I will take it
