### ISSUE TITLE
Convert the Security page https://emberjs.com/security/

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#18]
The goal of this issue is to recreate the Security page https://emberjs.com/security/  in an Ember app. The routing names and the content look should be the same as the live site. The currently deployed site is a Ruby app found [in a different repository](https://github.com/emberjs/website), and we are working towards converting the whole site over.

To get started with this issue, please add a comment that you are interested in helping out with it, and share your ideas for how to solve the issue. If you have questions, need to get someone's attention for feedback, or it's your first time contributing, the learning team can help you out! The best way to get in touch is to join the Ember Community Slack (https://ember-community-slackin.herokuapp.com/), click on "Channels", and join the #-team-learning channel. Thank you!

**Comment by abhilashlr** [comment]
@mansona I can work on this.

**Comment by mansona** [comment]
fixed by #74
