### ISSUE TITLE
Add the Sponsors page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#19]
## Goal
The goal of this issue is to recreate the page https://emberjs.com/sponsors/ in an Ember app.  The currently deployed site is a Ruby app found [in a different repository](https://github.com/emberjs/website), and we are working towards converting the whole site over.

## Criteria
- [ ] Add route: `/about/sponsors`
- [ ] The content look should be the same as the live site
- [ ] remove the top level route `sponsors` 
- [ ] use ember-styleguide components (and make notes where there is not an appropriate component)

## Additional Info
- To get started with this issue, please add a comment that you are interested in helping out with it. 
- If you have questions, need to get someone's attention for feedback, or it's your first time contributing, the learning team can help you out! The best way to get in touch is to join the [Ember Community Discord](https://discord.gg/emberjs) and join the #dev-ember-learning channel. Thank you!

**Comment by aklkv** [comment]
I am on it!
