### ISSUE TITLE
Add the "contribute to this page" back somewhere visible

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#198]
Before we converted this project into an Ember app there was a "contribute to this page" link at the bottom of the page that would link to the github repo. We need to add that back 👍

**Comment by mansona** [comment]
This issue is still relevant 👍 

@pichfl I don't know if this is something that we need to incorporate into the "content map" but we should definitely consider it in the redesign if possible

**Comment by mansona** [comment]
this is still relevant 👍

**Comment by cincodenada** [comment]
It looks like this can be closed with #637, I think? I came here because I didn't notice the contribution link but now that I look for it it's right there at the bottom
