### ISSUE TITLE
clicking brand link returns a 404? (is this unexpected behavior)

### ISSUE THREAD

**Issue by efx** [ember-learn/ember-website#207]
1. navigate to https://ember-beta-website.netlify.com/
2. click 'Brand' in the bottom left
3. You should see a 404 (https://ember-beta-website.netlify.com/brand) It redirects to https://emberjs.com/brand

**Comment by mansona** [comment]
nice catch @efx 🎉 as it happens this will be a problem for anything that is using the ember styleguide right now, not just the new website 🙈 

I have fixed this in #208 but it won't actually fix it until the site goes live 👍
