### ISSUE TITLE
Add the Mascot Commission page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#21]
## Goal
The goal of this issue is to recreate the page https://emberjs.com/tomster/commisson in an Ember app.  The currently deployed site is a Ruby app found [in a different repository](https://github.com/emberjs/website), and we are working towards converting the whole site over.

## Criteria
- [x] Add route: /mascots/commission
- [x] The content look should be the same as the live site
- [x] use ember-styleguide components (and make notes where there is not an appropriate component)
- [ ] make sure that you also implement the "commission sent" page from the old website that is intended to display once the form has been submitted. This doesn't necessarily have to be a route but you can do it that way if you like 👍 (if you don't then delete the `this.route('commission-sent');` route) 

## Additional Info
- When you submit a PR for this issue, please reference the issue so others can see that there is an existing PR. 
- If you submit a PR for this issue, please let us know in the dev-ember-learning channel with a message to the @core-learning team. 
- If you have questions, need to get someone's attention for feedback, or it's your first time contributing, the learning team can help you out! The best way to get in touch is to join the [Ember Community Discord](https://discord.gg/emberjs) and join the #dev-ember-learning channel. Thank you!

**Comment by patocallaghan** [comment]
@mansona I'll take this one 👍
