### ISSUE TITLE
Port all issues from the emberjs/website and archive

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#222]
This repository is a re-implementation of the Ember Website https://github.com/emberjs/website so we need to port over all of the relevant issues. 

Any of the issues that relate to the blog should be instead ported over to https://github.com/ember-learn/ember-blog

### Todo

- [x] Turn off heroku apps
- [x] Disable Dependabot
- [x] Port Issues
- [x] Port PRs
- [x] Port Projects

Once we are happy that everything we need has been ported to the corresponding repository then we can archive the https://github.com/emberjs/website repo

**Comment by MelSumner** [comment]
I did not disabled dependabot but the relevant things to port have been done. @locks can you disable dependabot? Or, is it automatically disabled by archiving the repo?

**Comment by sivakumar-kailasam** [comment]
It’s automatically disabled now that the original repo is archived(I’ve confirmed it)
