### ISSUE TITLE
Build the Blog system

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#23]
This will require significant broccoli development and will likely be implemented in a similar way to the new Ember Guides app.

This is likely work that will be done directly by @mansona but if anyone would be interested in a challenge please reach out on the #-team-learning channel in the Community Slack. Details of joining are on the [Community page on the website](https://emberjs.com/community/)

**Comment by Alonski** [comment]
An idea for when this is implemented. Would be cool to have a link at the bottom/top of a blog post with an `Edit on GitHub` link that links to the markdown and allows easy editing for creating PRs to fix mistakes :)

**Comment by mansona** [comment]
@Alonski yes that seems like a very useful feature 👍 can you add an issue to https://github.com/ember-learn/ember-ghost-ember-template so we can keep track of it? also, when writing the issue I would make a reference to https://github.com/ember-learn/guidemaker-ember-template/blob/master/app/templates/components/guides-article.hbs#L9 which is essentially the same feature but for the guides 👍

**Comment by Alonski** [comment]
@mansona Took a while but I did it :)

**Comment by mansona** [comment]
I'm closing this issue in favour of the project https://github.com/orgs/ember-learn/projects/15 👍
