### ISSUE TITLE
Port  "populate organisers data from meetup.com" functionality to new website

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#232]
I noticed that the [old website](https://github.com/emberjs/website)'s README had a section about "populating organisers data from meetup.com". Now I don't know if this is something that was ever done but this task is like a placeholder to investigate if this is functionality we need to port over to this repo 🤔 

Here is the section from the previous repo: 

--- 

**Note**: unless you're working with the API docs, don't use `rake preview`—use `middleman` (aka `middleman server`) instead.

To populate organizers data from meetup.com on [http://localhost:4567/meetups](http://localhost:4567/meetups)

  * get a [meetup API Key](https://secure.meetup.com/meetup_api/key/)
  * set `ENV["MEETUP_API_KEY"]`
  * run the following rake command

``` sh
rake findorganizers [force=true]
```

The force=true flag will overwrite all existing organizer data

**Comment by mansona** [comment]
I'm not sure if this is still relevant 🤔

**Comment by mansona** [comment]
this is still relevant 👍

**Comment by mansona** [comment]
@MelSumner do you have any idea if this is still relevant? 🤔 I don't see any mention of organisers in https://emberjs.com/community/meetups/ so I don't see why we would need to automatically populate this data from Meetup.com

Maybe we just close this?

**Comment by locks** [comment]
Closing as stale. Let's focus our efforts 💪
