### ISSUE TITLE
Add `ember-a11y-testing` to this repository

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-website#233]
It's one of Ember's goals to make sure that our sites meet accessibility standards. We have some work to do to make it as easy as we can to catch mistakes.

For this PR:
- install [ember-a11y-testing](https://github.com/ember-a11y/ember-a11y-testing)
- Write an acceptance test that visits each url in the website router, and calls the `a11yAudit` function (see the addon README for details)
- On failures, log a warning (instead of a hard failure) so that people can run this test suite and use it in their subsequent small PRs to fix the problems, rather than one "big bang" PR

You can learn more about ember-a11y and accessibility in general in [this Ember.js blog article](https://blog.emberjs.com/2018/06/17/ember-accessibility-and-a11y-tools.html)

**Comment by icole** [comment]
I will try to take a look at this. Discussed this with @jenweber in person at the contributors workshop to get started

**Comment by MelSumner** [comment]
Thank you for doing this work @icole !
