### ISSUE TITLE
Quick fixes needed for homepage accessibility bugs

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-website#234]
There are three easy-to-fix accessibility errors on our homepage, https://emberjs.com. These are important for people using assistive technology like screen readers.

Help out by editing the markup in https://github.com/ember-learn/ember-website/blob/master/app/templates/index.hbs. The screenshots below are the result of running an Accessibility Audit using Chrome's built-in web developer tools. If you run the audit, you'll be able to click on these in the console to see what elements are causing the problem. See the screenshot below for where to find the "audit" tab. Skip color contrast issues for now.

![Screen Shot 2019-03-16 at 11 44 08 AM](https://user-images.githubusercontent.com/16627268/54477736-d39c6800-47e0-11e9-81e2-d1b8f155df8d.png)

![Screen Shot 2019-03-16 at 11 44 45 AM](https://user-images.githubusercontent.com/16627268/54477752-fa5a9e80-47e0-11e9-9d7d-f20f9c0598e5.png)

![Screen Shot 2019-03-16 at 11 47 42 AM](https://user-images.githubusercontent.com/16627268/54477782-66d59d80-47e1-11e9-833f-7d62375c723b.png)

**Comment by alexpark90** [comment]
Hi, I am a newbie on OSS world and would like to make my first contribution. I have run Accessibility audit on your homepage, and found 4 issues. Could you clarify if you want me to fix all these 4 or just 3 that you mentioned above. Thank you!

![accessibility](https://user-images.githubusercontent.com/11951198/54482340-38bf8000-4818-11e9-91e0-9843c4863736.JPG)

**Comment by jenweber** [comment]
@alexpark90 good question. Skip the "color contrast" issues for now, since the home page redesign that's in the works has a new color palette.

**Comment by jenweber** [comment]
P.S. thanks for your help! Please get in touch if you have any questions. [Ember Community Discord](https://emberjs.com/community/) has a #dev-ember-learning channel that is a great place to ask questions if you need a quick answer.

**Comment by alexpark90** [comment]
Hi @jenweber, while inspecting the code, I have realized that the component templates to be edited are actually from [ember-styleguide](https://github.com/ember-learn/ember-styleguide). Is it okay if I open a ticket there and work on them? I have created pr for html language attribute addition though.

**Comment by jenweber** [comment]
That would be great, thanks!

**Comment by jenweber** [comment]
I think we should keep this one open and evaluate if these things have been fixed by other PRs since

**Comment by jwithington** [comment]
I'm wondering if the audit is catching the links that are created by the homepage users model, here:

```
  <ul class="homepage users">
    {{#each model.users as |user index|}}
      <li class={{concat "user " (if (gte index 4) "desktop-only")}}>
        <a href={{user.url}} rel="nofollow">
          <img
            src={{asset-map (concat "images/home/" user.file)}}
            width="210"
            height="103"
            alt={{user.alt}}
          >
        </a>
      </li>
    {{/each}}
  </ul>
```

I considered updating the model to add a label for each link, but realized it would quickly just be something like "Visit the Microsoft Site," "Visit LinkedIn," etc., and that seemed excessive/unnecessary. If it's not, I can definitely do it. 😀

**Comment by amyrlam** [comment]
I merged https://github.com/ember-learn/ember-website/pull/429 from @jwithington!

I am not sure about the question above https://github.com/ember-learn/ember-website/issues/234#issuecomment-543401201
