### ISSUE TITLE
Update the Ember Styleguide

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#239]
### The goal

This website is using the [ember-styleguide](https://github.com/ember-learn/ember-styleguide) directly as a github dependency. This was required to move quickly while we were trying to get the website deployed. 

We need to update the dependency manually using npm.

### Specific implementation advice

I think the easiest way to update github dependencies on npm is to just run `npm i -D github:ember-learn/ember-styleguide` (i.e. exactly what it is in the package.json)

### Notes

If you have multiple thousands of lines changed in your package-lock.json as a result of this change you probably need to update npm to the latest and try again.

**Comment by dbollinger** [comment]
I can do this one

**Comment by mansona** [comment]
Fixed in #242
