### ISSUE TITLE
Missing Voestalpine image in "Who uses Ember.js"

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-website#258]
@fpauser Moving https://github.com/emberjs/website/issues/3862 here. Can you submit a PR changing the logo to a `.png` for now? Looks like all of the other files [here](https://github.com/ember-learn/ember-website/tree/master/public/images/users) are `.png`. 

Perhaps we can allow .svg as a separate issue?

**Comment by amyrlam** [comment]
I just saw https://github.com/ember-learn/ember-website/pull/252...need to investigate.

**Comment by MelSumner** [comment]
Resolved with #278 👍

**Comment by amyrlam** [comment]
thanks!
