### ISSUE TITLE
Pull from json for beta?

### ISSUE THREAD

**Issue by rwwagner90** [ember-learn/ember-website#263]
@rwjblue should we pull the current beta version from http://builds.emberjs.com/beta.json to auto update the beta version and where we are on the progress to the next release?

**Comment by rwwagner90** [comment]
Do we still need to do this?

**Comment by rwwagner90** [comment]
@rwjblue have we done this?

**Comment by rwjblue** [comment]
Don't think so?

**Comment by rwwagner90** [comment]
So we are still manually updating the numbers?

**Comment by locks** [comment]
Yeah. I'm closing this one because we should rethink the whole releases page to be more self-sustaining.
