### ISSUE TITLE
Communicate that Ember js/data/cli are on a shared release cycle

### ISSUE THREAD

**Issue by joukevandermaas** [ember-learn/ember-website#265]
The current builds page only really mentions Ember.js, but the Ember project now consists of at least three components: Ember.js, Ember Data and Ember CLI. The landing page's copy should be updated to include the following information:

1. Ember JS/CLI/Data are on a shared six-week release cycle
2. They have the same major/minor version number (but can have different patch versions)
3. **(maybe)** the best way to get the latest everything is to use the blueprints shipped with Ember CLI (i.e. just run `ember new`)

**Comment by MelSumner** [comment]
The current releases page gives this information, so closing this issue. Apologies that it took us so long to respond.
