### ISSUE TITLE
Make a pretty LTS graph

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#266]
See @mixonic's graph in [Announcing Ember's First LTS](http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html).
[Node's LTS schedule](https://github.com/nodejs/LTS#lts_schedule) also has a similar graph.

Using d3 possibly? Should be self-updating with manual overrides. This could be developed as a tidy lil' component so we don't bikeshed about where it should go.

**Comment by mansona** [comment]
So this has been somewhat implemented in https://github.com/ember-learn/ember-website/pull/334 and I have mentioned to @jenweber about potentially incorporating it into https://github.com/ember-learn/ember-website/pull/351 but if we don't think it fits then we can close this issue and close this PR 👍

**Comment by mansona** [comment]
let's keep this open 👍

**Comment by fozy81** [comment]
Some additional notes, after a little investigating and trying out a few approaches (keep in mind I'm a complete novice and barely know enough SVG to be dangerous!):

**General considerations**
- Do we require both a stylised semver gant chart and additionally a maintenance schedule (bug fixes/security)? They are slightly different and may be too much info to put on one diagram/chart.
-  How best to pull together/centralise all the data/dates for all versions, releases, lts, maintenance etc whilst maintaining a single source of truth. Is there potential for further automation (whilst allowing manual tweaks)? 

**Using npmjs lts package**
Pros:
- Off the shelf
- Easy data format
- Displays maintenance schedule and timings clearly

Cons:
- Uses slightly different terminology than we currently use 'Current', 'Active' and 'Maintenance' - so may take extra work in terms of re-drafting / describing these terms across the releases pages.
- Doesn't show the gant chart style semver 'merging' 
- Adds dependencies (D3 etc)

**Rolling our own D3, SVG (or Highcharts?) diagram**
Pros:
- Can customise

Cons:
- Dealing with date time (in pure svg?!)
- Potentially adds dependencies (D3, Highcharts-gant.js etc)

**Work so far**
A rudimentary svg maintenance chart for LTS only (as a glimmer component):
![image](https://user-images.githubusercontent.com/2878163/112643070-dd2f2080-8e3b-11eb-8a2c-3be7c10eabd9.png)

Happy to help on this further (which ever approach is selected).
