### ISSUE TITLE
Possible additional items to add to the status board

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-website#271]
- [ ] Statusboard (`#-team-learning`)
- [ ] Marketing/website push  (`#wb-marketing` / `#st-website`)
- [ ] Infrastructure modernization: dog-fooding our work (`#-team-learning`)
- [ ] Ember Data modernization. Could make folks nervous, so let's be careful on how we describe this  (`#dev-ember-data`)
- [ ] jQuery removal. Could also make folks nervous to hear us wondering about this (`#dev-jquery-removal`)
- [ ] Tutorials: RFC for it? (`#st-tutorials`)

**Comment by MelSumner** [comment]
Closing this issue in favor of the re-vamped status board project planning. 👍
