### ISSUE TITLE
Fix footer icons

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-website#274]
They are broken because they depend on a font that's not installed. Rather than add the font, locate the github, twitter, and google plus SVGs used in Ember-API-docs, save them, and replace the icons in the footer.

This is a temporary fix until the Ember-styleguide component is ready.

**Comment by MelSumner** [comment]
@jenweber is this still an issue?

**Comment by MelSumner** [comment]
Reviewed the site and it doesn't seem to be an issue anymore, so I'm closing this issue.
