### ISSUE TITLE
Add an IDE/Editor Page/Section to Site

### ISSUE THREAD

**Issue by Alonski** [ember-learn/ember-website#294]
### The goal

Ember currently doesn't have a single source of truth regarding info on using Ember with IDEs/Editors. 

For example, we could link to useful extensions, types, and other topics that could be useful.
Another important topic that could be discussed is the [Ember Language Server](https://github.com/emberwatch/ember-language-server).
This was sparked by a question that I and locks have answered multiple times in the past year: https://discordapp.com/channels/480462759797063690/486516209873846292/561830418270126091

We could create something that would show up in Search Engines as it would have authority behind it.
People will still ask questions but at least then we will have a place to send people to

### Specific implementation advice

Need to decide if it should be a short section the https://emberjs.com/learn/ page or its own page that is linked from there.

### How to get started

We need to create a list of popular IDEs/Editors that we would like to have in this page/section.
We need to find people to Champion various IDEs/Editors.
We need to discuss how this will work exactly. @locks expressed concerns that the quality for each section will vary wildly depending on the champion.

[@madnificent](https://github.com/madnificent) has volunteered to champion for Emacs.
I, @Alonski could champion VSCode and would love to have help with it.

For reference here is the initial chat about it on Discord: https://discordapp.com/channels/480462759797063690/480777444203429888/561839648675201034

**Comment by shankarsridhar** [comment]
I like this idea 😃 .
@Alonski,  Assuming this is going to be done, I would love to help, if more help is needed on this.

**Comment by Alonski** [comment]
@shankarsridhar We haven't started work on this yet. If you are willing to help push this forward that would be awesome

**Comment by shankarsridhar** [comment]
@Alonski Sounds good. But, I use only `Vs Code` for authoring my ember apps. 😄. Not sure if that matters.

**Comment by Alonski** [comment]
@shankarsridhar The initial work would be designing this page with at least a skeleton for different IDE/editors. Then VSCode could be the first.

**Comment by MelSumner** [comment]
@Alonski this changes over time and I don't currently see a way to keep this information up to date. If anyone is going to propose something, it needs to include a plan for long-term maintenance.

**Comment by Alonski** [comment]
It would be as up to date as any other section of the site. I believe that once it is built the maintenance on it will be minimal.
There are a lot of questions regarding HBS in VSCode, setting up Ember in VSCode etc that are easy to answer but currently there is no "one place" to put the answers.

This is an idea. I don't have the bandwidth right now to create something like this from scratch. If someone else was willing to champion it that would be awesome

**Comment by ryanolsonx** [comment]
I'd be willing to champion Vim. 🥇 

I agree with @Alonski. It shouldn't be much work to keep this up to date.

I think it would be really cool to follow a pattern like [Dracula Theme's](https://draculatheme.com/) site for each editor (page per editor).  If we had a page per editor, we could give really good instructions on how to develop Ember.js in each.  For example, VS Code's page might have a few links to VS Code extensions, while Vim's might have a few sections that show which plugins to install and how to configure things from scratch to use the plugin.

**Comment by Alonski** [comment]
I recently learned about this:
https://cli.emberjs.com/release/appendix/dev-tools/

It seems that we could work together to update this?

**Comment by ryanolsonx** [comment]
Can someone close this issue and we can focus on ember-learn/cli-guides? Unless that's not the right place for that documentation....

**Comment by MelSumner** [comment]
Closing this issue.
