### ISSUE TITLE
Use unique titles for each page

### ISSUE THREAD

**Issue by j-brennan** [ember-learn/ember-website#313]
As a follow up to https://github.com/ember-learn/ember-website/issues/93, just opening this up to see if there is a desire to make each page have it's own dynamic page title?

Currently each page uses the title: `"Ember.js - A framework for ambitious web developers"`. Would it be useful to see different titles for each page. e.g. the Legal page uses `"Ember.js - Legal"` etc.

**Comment by mansona** [comment]
@MelSumner I assume this is really a question for the SEO team? I can definitely work on a mechanism that would allow us to change the title dynamically (with a fallback) but I think we need to answer the question "do we need this" first 🤔

**Comment by MelSumner** [comment]
@mansona we absolutely need this. It's an accessibility thing that we don't update the page titles. 

However, the page title format should be PageName - SiteName.

**Comment by ryanolsonx** [comment]
Should we also make this change for the new rfc branch? I submitted a PR for master.

**Comment by ryanolsonx** [comment]
Can someone close this (now that the PR has been merged)?

**Comment by MelSumner** [comment]
@ryanolsonx yup! thank you for your help!
