### ISSUE TITLE
Update links on /releases/canary because of Amazon S3 functionality change

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#316]
In short, it seems `//s3.amazonaws.com/<bucketname>/key` will no longer be supported to be replaced with `//<bucketname>.s3.amazonaws.com/key`. More information can be read on the [official AWS announcement](https://forums.aws.amazon.com/ann.jspa?annID=6776)

This issue is blocked until we figure out what the new links are. Conversation on this aspect of the issue should be had on the twin issue: https://github.com/ember-cli/ember-source-channel-url/issues/59.

**Comment by rwjblue** [comment]
I think this means that we will loose the ability to use HTTPS for these requests (without additional hoop jumping that is). We may need to change the bucket name to avoid including a period.

**Comment by mansona** [comment]
@locks can you be a bit more specific about what this issue has to do with the website? 🤔 I am assuming this has something to do with the release route but I don't follow what the issue is and what needs to change on this end.

**Comment by locks** [comment]
@mansona the links in https://emberjs.com/releases/canary will stop working soon-ish.

**Comment by mansona** [comment]
@locks I have updated the title and description to reflect that 👍

**Comment by mansona** [comment]
@rwjblue is this still an issue? 🤔 I seem to remember you mentioning something about them rolling back this decision but I could be making that up 😂

**Comment by rwjblue** [comment]
Ya, they just delayed the change. We should still address IMHO.

**Comment by mansona** [comment]
@rwjblue do we know what the new links should be?

**Comment by locks** [comment]
Keep open.

**Comment by rwjblue** [comment]
Amazon updated there policy, the link above now states:

> On April 30, 2019, we posted a deprecation announcement of path-style requests (see below). In response to feedback on the original deprecation plan, we are making an important change. Here is a summary, and please view this Jeff Barr Blog for more details:
> 
> Original Plan: Support for the path-style model ends on September 30, 2020 (see below).
> 
> Revised Plan: S3 buckets created after September 30, 2020 will support only virtual-hosted style requests. Path-style requests will continue to be supported for buckets created on or before this date.

As stated above, this means it only applies to **new** buckets created after 2020-09-30.
