### ISSUE TITLE
[redesign] Add batteries included section to the homepage

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#365]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

![Wide](https://user-images.githubusercontent.com/594890/63088022-96810100-bf4b-11e9-8fc7-8a56efc42df6.png)

Add the Batteries Included section to the homepage. Some of the images/illustrations are missing from this screenshot so just ignore them for now.

## Todo

- [x] create images from the sketch file for the terminal and browser window
  - [terminal-browser.svg.zip](https://github.com/ember-learn/ember-website/files/3505135/terminal-browser.svg.zip)
- [ ] add content using the layout classes
  - Here is the content so you don't have to type everything out: https://gist.github.com/mansona/c627d2495b127737203d513d7fdb9b3b

## useful documentation

- https://deploy-preview-145--ember-styleguide.netlify.com/concepts/layout

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason. To see the documentation of the styleguide you can go to https://deploy-preview-145--ember-styleguide.netlify.com/

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by balinterdi** [comment]
I'll tackle this.

**Comment by balinterdi** [comment]
@mansona I started working on this but realized the screenshot above looks really different than the design screenshot in [the original RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md).

I think the sketch file matches the original RFC image but I'm not sure as I don't have a Sketch license so I get a modal in my face and can only see the very top of the "Batteries included" section (which has a dark background).

Which is the authentic source? Thank you.

**Comment by mansona** [comment]
This screenshot is the correct source, it's from the updated sketch file that I sent you which has had a number of changes (including the mobile view which wasn't in the original RFC at all)

Do you need me to extract anything from the sketch file for you?

**Comment by balinterdi** [comment]
Which screenshot? :) The one here, above? It's different from the Sketch file, as far as I can tell.

**Comment by mansona** [comment]
@balinterdi I'll DM you the answer to this because I'm likely confusing things 🙈

**Comment by mansona** [comment]
Implemented in https://github.com/ember-learn/ember-website/pull/383
