### ISSUE TITLE
[redesign] add content for the Ember Ecosystem section on the landing page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#366]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

<img width="743" alt="Screenshot 2019-07-25 at 11 07 41" src="https://user-images.githubusercontent.com/594890/61866173-9baedb00-aecc-11e9-86e6-1b368e3a85b2.png">

Add content for the Ember Ecosystem section on the homepage.

## Todo

- [ ] extract the images from the sketch file
- [ ] add content and images using the layout classes

## useful documentation

- https://deploy-preview-145--ember-styleguide.netlify.com/concepts/layout

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason. To see the documentation of the styleguide you can go to https://deploy-preview-145--ember-styleguide.netlify.com/

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by mansona** [comment]
@ghislaineguerin do we need to think about "grey background" for this one?

**Comment by ghislaineguerin** [comment]
@mansona I think so. we have .bg-muted for that case, it's on the guide.
