### ISSUE TITLE
[redesign] add content for the community section of the landing page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#367]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

<img width="743" alt="Screenshot 2019-07-25 at 11 20 48" src="https://user-images.githubusercontent.com/594890/61867141-6905e200-aece-11e9-80c7-9aa8b4ab3b00.png">

Add the content for the community section of the landing page.

## Todo

- [x] extract images from the sketch file
- [ ] add content and images using the layout classes

## useful documentation

- https://deploy-preview-145--ember-styleguide.netlify.com/concepts/layout

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason. To see the documentation of the styleguide you can go to https://deploy-preview-145--ember-styleguide.netlify.com/

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by mansona** [comment]
Here are the images to use for now. We can worry about the right images and optimizing them later.

[Archive 2.zip](https://github.com/ember-learn/ember-website/files/3501531/Archive.2.zip)

**Comment by betocantu93** [comment]
I can do this one

**Comment by MelSumner** [comment]
Please see the notion docs for the new images

**Comment by pichfl** [comment]
Updated images for both wide and narrow screens.

<img src="https://user-images.githubusercontent.com/194641/63848010-49f7e580-c98f-11e9-9440-ca957dbe5a78.png" alt="section-community" width="70%"> <img src="https://user-images.githubusercontent.com/194641/63848009-49f7e580-c98f-11e9-9467-bc580bbaa026.png" alt="section-community-narrow" width="20%">

**Comment by mansona** [comment]
closed in #386
