### ISSUE TITLE
[redesign] add content for the "Ready to start shipping" section on the homepage

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#369]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

![Wide - shipping](https://user-images.githubusercontent.com/594890/63420565-d4c06980-c3fe-11e9-8211-a2da2907be0a.png)

Add the content for the "ready to start shipping" section

## Todo

- [ ] add content using the layout classes

## useful documentation

- https://deploy-preview-145--ember-styleguide.netlify.com/concepts/layout
- https://website-redesign-rfc--ember-styleguide.netlify.com/css/helpers#dark

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason. To see the documentation of the styleguide you can go to https://deploy-preview-145--ember-styleguide.netlify.com/

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by balinterdi** [comment]
I'll tackle this.

**Comment by mansona** [comment]
fixed in https://github.com/ember-learn/ember-website/pull/392
