### ISSUE TITLE
[redesign] Fill in new illustrations for the batteries included section

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#384]
The "batteries included" section has been merged as of https://github.com/ember-learn/ember-website/pull/383 and is currently using dummy images to fill in the gaps for missing illustrations.

This issue is to track both the generation of those illustrations and adding them to the website 👍 

## Todo

- [x] Routing
- [x] Data layer
- [x] Testing
- [x] Performance
- [x] Easy upgrades

**Comment by mansona** [comment]
This is not about creating new illustrations, instead it is us just listing what we want for each of these illustrations so that we can get them created by the illustrator.

e.g. if we decide that we want a "code sample" and a rendered picture of what it looks like for any particular section this does not need to be sent to the illustrator.

It is also ok to say "I don't know" for any of the sections 😉

**Comment by pichfl** [comment]
#### Routing

Should highlight a browser URL bar with a route and could show a snapshot from 

#### Data layer

Depends on how silly we want to have this. A tomster with a stack of records and tapes would be very cute.

#### Testing

Logos of Q-Unit, etc. and maybe a green traffic light? 

#### Performance

I think this is where the Octane hamsters could shine. Not sure if we should show anything proper. Maybe the Glimmer.js logo?

#### Easy upgrades

No idea.

**Comment by ghislaineguerin** [comment]
@MelSumner Did you hear back from the illustrator regarding the list above?

**Comment by mansona** [comment]
We discussed this in the meeting today and if we don't have the new illustrations by the time it comes to finish this project (and potentially release) then we should come up with some illustrations ourselves

note: this is at the bottom of this list in the project because it is much lower priority than other things

**Comment by mansona** [comment]
fixed in #559
