### ISSUE TITLE
Copy content for new landing page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#393]
Make sure all questions on https://www.notion.so/emberteam/Home-74030c0503ac4c04b88aa621640fc0e6 are answered and update content in index.hbs accordingly

**Comment by mansona** [comment]
Also make sure that the 20-minute "rough draft" of the remaining "batteries included" sections are actually reviewed 👍

**Comment by aalimovs** [comment]
Is the notion link private on purpose? I want to give some feedback on copy that I saw at https://deploy-preview-361--ember-website.netlify.com/, not sure where's best to do that?

**Comment by mansona** [comment]
@MelSumner I assume we can close this now that we have released? or was there more copy that you still wanted to update?

**Comment by mansona** [comment]
@aalimovs now that we are live you can either discuss it in Discord, create an issue or create a PR with suggestions. If it's a substantial change I recommend either opening an issue or discussing it in Discord before opening a PR 👍
