### ISSUE TITLE
Decide if we need to re-introduce "importance of issues by years of experience" graph

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#422]
As part of https://github.com/ember-learn/ember-website/pull/421 in an effort to reduce the asset size of the website I needed to remove the only "columnrange" graph that we were using because it is using a highcharts module that we don't really have a good way to load dynamically now that we are loading highcharts dynamically 

I would have replaced the graph with something that still communicates the message, but I was not really sure what this chart was trying to communicate 🙈 

<img width="1021" alt="Screenshot 2019-10-06 at 14 09 15" src="https://user-images.githubusercontent.com/594890/66269821-2739d600-e845-11e9-87e8-b80762430498.png">

We have two options on how to proceed: 

1. Figure out what this chart was trying to say and replace it with a chart that does not require a module to render with highcharts. or: 
2. leave this chart out of the survey and don't look back 🎉 

I would be in favour of (2.) above because it seems like this specific chart was never repeated since it was first used in 2017. I also wonder how much value this chart has been providing in general as it seems really quite confusing.

Thoughts?

**Comment by rwjblue** [comment]
Probably a stupid question, but since we don't really need it to be dynamic could we render it as an image / svg and inline that instead?

**Comment by sandstrom** [comment]
I'd vote for (2)

**Comment by MelSumner** [comment]
@mansona is this still an issue?

**Comment by mansona** [comment]
@mansona yes it still needs to be resolved. I like the idea that @rwjblue proposed about using a static SVG so we might do that 👍
