### ISSUE TITLE
[redesign] Community Page - Update Markup

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#432]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

## To Do: 
- [ ] Update the markup for the `/community` page

--- 

### Notes (important) 

This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and is one of the **last remaining issues** before we are ready to release. As we are moving very quickly on this project you should comment on this issue that you are taking it on so that we do not have multiple people working on the same issue. **Note:** please don't take on an issue if you do not think you can complete it within 24 hours 🙏 

This issue is **strictly to only update the markup** of a page on the website and should be possible to do using only components and class helpers in the new [ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/).

If you find that you need to create page-specific styles, complete the page as best you can and open a PR **without** adding any styles. Make a note in your PR what was missing from the styleguide that prevented you from completing the page.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

**Comment by ijlee2** [comment]
I can work on this issue.

**Comment by mansona** [comment]
@ijlee2 thanks a million for your feedback on the styleguide documentation 👍 I have a PR that will simplify things quite a lot so hopefully when you get a few minutes in future it will be much simpler 👍 

https://github.com/ember-learn/ember-website/pull/448

**Comment by mswanson** [comment]
I can pick this up unless @ijlee2 wants it.

**Comment by ijlee2** [comment]
Nah, go for it, @mswanson. Thanks!

**Comment by mansona** [comment]
closed in #456 🎉 

(I really don't know why these aren't auto closing any more 🙈 )
