### ISSUE TITLE
[redesign] global content background

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-website#453]
While the body of the page should remain `#fff`, the `<main>` element should be colored `#F4F6F8` to match the designs and to ease the sharp white.

**Comment by MelSumner** [comment]
We can set the body background to be the same as the main.

**Comment by pichfl** [comment]
The `<body>` should remain `var(--color-white)`, to ensure super short pages render correctly (the footer ends in plain white in the design). 

`<main>` should use `var(--color-gray-100)` (which is the updated / better value than the hex value above).

**Comment by mansona** [comment]
@pichfl can you confirm that this is in fact now done? It looks done on the latest version of the styleguide/website 🤔

**Comment by pichfl** [comment]
Whops, forgot to close this. Yes, this was done a few weeks ago via a new release of ember-styleguide.
