### ISSUE TITLE
Change ecosystem svg

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#459]
The ecosystem SVG should be changed to use VS Code instead of Atom. (or something else, just not Atom). 

![image](https://user-images.githubusercontent.com/4587451/67970940-df0a9b00-fbd9-11e9-9ba3-d4d8c9bb7706.png)

**Comment by mansona** [comment]
@MelSumner why not atom? 🤔

**Comment by mansona** [comment]
Fixed in #529
