### ISSUE TITLE
consider authoring specific page meta:descriptions

### ISSUE THREAD

**Issue by oliverlangan** [ember-learn/ember-website#479]
I notice that link previews to the Ember website (in Slack) have customized titles but always show the same description.

The descriptive text is good for the top-level of the site, but could be more useful if it described the page better.

![Screen Shot 2019-12-03 at 14 51 02](https://user-images.githubusercontent.com/182776/70096714-8e250280-15dc-11ea-9daf-3fe5ddb0d03d.png)

**Comment by amyrlam** [comment]
@oliverlangan Thanks for the report. This may be addressed by the Website Redesign RFC (issues here: https://github.com/ember-learn/ember-website/labels/Website%20Redesign%20RFC). Let's keep this issue open and revisit when that it out

**Comment by mansona** [comment]
Just looking at the original reported issue, this isn't part of the ember-website but instead it's part of the blog. This will get fixed as part of https://github.com/orgs/ember-learn/projects/15 but shouldn't be part of the Website Redesign project 👍

**Comment by oliverlangan** [comment]
This does still appear to be an issue: the 'description' text for the link is still a default snippet of text.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/182776/84839963-20c64580-aff3-11ea-881b-6fb4a2144733.png">

I am referring to the 'blockquoted' text here: "Ember.js helps developers be more productive out of the box. Designed with developer ergonomics in mind, its friendly APIs help you get your job done—fast."

I understand that this is a link to the blog, not the main site: but I don't see any issue that mentions it in the blog redesign project.
