### ISSUE TITLE
[Redesign] Considere using focus-visible

### ISSUE THREAD

**Issue by josemarluedke** [ember-learn/ember-website#527]
I have been following the redesign effort and I would like to start a discussion about the focus state. 

The focus indicator is essential for keyboard navigation and accessibility. However, for users using a mouse or trackpad, the focus indicator can be a little distracting. Below are a few examples that I find super distracting. 

There is a solution that allows hiding the focus indicator when using a mouse, and show them when keyboard is used. 

This is such a common use case that it's being implemented directly into browsers: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

In my projects, I always use this "polyfill" that works great: https://github.com/WICG/focus-visible

You can also find an example using that lib here: https://josemarluedke.github.io/frontile/versions/master/docs/core/accessibility/focus-management

Here is what I'm referring to:

<img width="541" alt="Screen Shot 2020-01-17 at 10 16 21 AM" src="https://user-images.githubusercontent.com/230476/72635842-a34abc00-3912-11ea-903c-b241e8bb5c73.png">
<img width="390" alt="Screen Shot 2020-01-17 at 10 16 26 AM" src="https://user-images.githubusercontent.com/230476/72635843-a34abc00-3912-11ea-94d5-1278acd58568.png">
<img width="281" alt="Screen Shot 2020-01-17 at 10 16 46 AM" src="https://user-images.githubusercontent.com/230476/72635841-a34abc00-3912-11ea-9587-13b939412643.png">

cc/  @mansona @MelSumner

**Comment by MelSumner** [comment]
We don't plan to remove focus, but we do plan to update the styleguide to ensure that the focus outline is on-brand for the rest of the design.

Thank you for submitting this issue- I have it documented in ember-styleguide (where our styling lives) so I will close this issue and track it there- https://github.com/ember-learn/ember-styleguide/issues/285

**Comment by Windvis** [comment]
@MelSumner Can you elaborate on why the focus styles are needed when the user is using mouse navigation? Just trying to understand the reasoning behind always showing the focus state, since @josemarluedke's explanation seemed very reasonable to me. :smile:
