### ISSUE TITLE
Add a statusboard page back (with the same url as it used to have)

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#544]
Make it look something like the Editions page, linking out to other resources

- rfcs repo
- rfc tracker project

**Comment by mansona** [comment]
@MelSumner I have moved this into the Phase 2 project as we agreed that it wasn't a blocker for release of the website 👍

**Comment by MelSumner** [comment]
Yes, we are also not going to put it back until we have a good path forward for this project in general. It might be a good learning team discussion during the f2f at EmberConf.

**Comment by miguelcarvalho13** [comment]
Hi! Can I help with this?
Is this related with this PR https://github.com/ember-learn/ember-website/pull/332?
