### ISSUE TITLE
Logos are in (some) color instead of in grayscale

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#547]
How it looks on the redesign branch: 
![image](https://user-images.githubusercontent.com/4587451/73947820-ba4f4f00-48bd-11ea-92d5-a2abda352d1e.png)

How it should look: 
![image](https://user-images.githubusercontent.com/4587451/73947849-c76c3e00-48bd-11ea-9220-38d0d5bbdce3.png)

**Comment by pichfl** [comment]
I'll take care of exporting the images.
