### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#548]
- update background colors
- spacing is too tight
- Copyright text and "generously supported by" text is too large
- supporting companies' logos show orange tick on hover
- focus outline needs correcting (the color can be changed but focus outline can't be removed)

##### Desktop
![footer @large](https://user-images.githubusercontent.com/194641/74053158-89fdd280-49db-11ea-9434-0ae00f7e3cb2.png)

##### Mobile
![footer @small](https://user-images.githubusercontent.com/194641/74053177-92eea400-49db-11ea-8d2f-4d766b1755dc.png)

**Comment by mansona** [comment]
The new design is updated in the abstract in the "homepage collection"

**Comment by ddoria921** [comment]
Looks like this needs to be fixed in the ember-styleguide, right? Either way I'd like to take a shot at tackling this

**Comment by pichfl** [comment]
@ddoria921 that is correct 🙂

**Comment by mansona** [comment]
fixed in https://github.com/ember-learn/ember-styleguide/pull/295
