### ISSUE TITLE
background elements

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#550]
See screenshot- see if we can add some background grid dots in the Ember Ecosystem and Batteries included section. 

Not a blocker. 

![image](https://user-images.githubusercontent.com/4587451/73949590-3ba7e100-48c0-11ea-90a6-34157eea6fa0.png)

**Comment by mansona** [comment]
As this is not a blocker I'm going to move it to phase 2 for now 👍

**Comment by jeffdaley** [comment]
@MelSumner Do you have a screenshot of how the "batteries included" section should look?

**Comment by oo6** [comment]
The grid dots cover part of the text and tabs, so can't select or click

<img src="https://user-images.githubusercontent.com/6327995/103846765-c9480e00-50d9-11eb-90d9-14ed3c45789d.png" width="400">

**Comment by ijlee2** [comment]
@oo6 Thank you for reporting the issue!

@jeffdaley Can you create a bug fix PR? I briefly looked at `<GridDots>` component's template, and am not sure yet whether the solution would be to update the `<svg>` definition or to do something else.

**Comment by jeffdaley** [comment]
@oo6 Great catch.

Just submitted a PR addressing this issue.

**Comment by MinThaMie** [comment]
They're there :) So I'm going to close this issue. @jeffdaley thanks for your contribution!
