### ISSUE TITLE
At smaller breakpoints, logos are still inline

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#564]
Screenshot: 
![image](https://user-images.githubusercontent.com/4587451/74479263-77b8e400-4e74-11ea-8e9a-025672c56bfd.png)

Expectation: 
When at smaller breakpoints, these logos should not still present in the same way they do on larger breakpoints.

**Comment by mansona** [comment]
@MelSumner do you see this as a blocker for release?

**Comment by alexeykostevich** [comment]
@MelSumner , I see the expected design for large screens (https://github.com/wifelette/rfcs/blob/master/text/0425-website-redesign.md), but, unfortunately, was not able to find the design for smaller screens. Please, could you let me know if there are any wireframes available?

Am I right that company names should be stacked up vertically on a particular breakpoint (as, for example, https://vuejs.org does)?

Currently, the logos represent a single SVG file (https://emberjs.com/images/home/landing-logos.svg). If different layout for different screen sizes is needed, we need to break this SVG down into multiple files (one per logo).

Can we proceed with this change?
