### ISSUE TITLE
[Redesign] Link to Ember Observer

### ISSUE THREAD

**Issue by Windvis** [ember-learn/ember-website#566]
The Ember Observer section on the new landing page is a nice addition and looks sweet, but it seems the link to the website is missing? :smile:

**Comment by amyrlam** [comment]
@Windvis Sorry this has been open for awhile. Do you mean https://github.com/ember-learn/ember-website/blob/94039e9f7c99348dc7eb4b9430b1d95d59586bf1/app/templates/learn/index.hbs#L100, looks like it has a link? Can also take a look when the website is back up, date TBD

**Comment by Windvis** [comment]
No problem! I haven't been following up with coding related things since I've gone AFK for the last couple of months.

It's been a while since I saw the landings page but I _think_ I was talking about [this section](https://github.com/ember-learn/ember-website/blob/9b837262c8f53f0890bfc6188accdcdc8c58d22a/app/templates/index.hbs#L133). People who don't know ember observer might want to take a look after reading that section, so adding a link there would make sense IMO. Hard to say without seeing the page, and I don't have a local running copy anymore.

But I can close this issue for now and reopen it once the landings page has been restored, and it's still a "problem"?

**Comment by amyrlam** [comment]
@Windvis thanks for the context! Let's keep it open, I can make a quick fix when the code is back up. I rolled back and totally see what you mean now
