### ISSUE TITLE
Make the AddonTabs component fully keyboard accessible

### ISSUE THREAD

**Issue by Windvis** [ember-learn/ember-website#567]
It seems that it's not possible to switch to the other tabs with keyboard based navigation alone at the moment. 

![image](https://user-images.githubusercontent.com/4587451/74659018-23a24e00-5159-11ea-9d8d-2f5079c8fdad.png)

Expected behavior:
- Pressing `TAB` should cause focus to the row of tabs
- Left or right arrow keys should cause movement inside of the tab list 
- pressing `ENTER` should activate the new tab and show the corresponding content

The current behavior of pressing `TAB` while a tab is active is correct (it focuses on the tab content itself and then continues to travel down the tabindex. 

References:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role
- https://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by Windvis** [comment]
@MelSumner I can pick this up :) I have a WIP local branch for this already.

**Comment by MelSumner** [comment]
@Windvis sure! Thank you!

**Comment by mansona** [comment]
Fixed in #585
