### ISSUE TITLE
Bug: https://emberjs.com/releases/ is not up to date

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-website#568]
See comment here: https://discuss.emberjs.com/t/ember-js-ember-3-16-released/17507/2, when you go to http://emberjs.com/builds/ it still shows 3.15

Took a look at https://github.com/ember-learn/ember-website/blob/master/app/models/project.js but not sure what's wrong, any ideas?

Aside: Submitted update for it to be https://emberjs.com/releases/, not /builds redirect ... here https://github.com/ember-learn/ember-blog/pull/534

**Comment by locks** [comment]
https://github.com/ember-learn/ember-website/tree/master/data/project/ember and https://github.com/ember-learn/ember-website/tree/master/data/project/emberData need to be manually updated!

**Comment by amyrlam** [comment]
@locks thanks, let me take a looksie

**Comment by happydude** [comment]
https://emberjs.com/releases/ appears to be behind again, it shows "3.18.0 Released May 3" and "3.19.0 Coming the week of May 24"

**Comment by amyrlam** [comment]
@happydude thanks for the ping! This is a known issue, and there's some discussion around the best way to fix this on this PR: https://github.com/ember-learn/ember-website/pull/655

The blog tends to be a more reliable way of tracking releases, but sometimes the blog post comes later than all the releases: https://blog.emberjs.com/tags/releases.html 

Sorry to not have a better answer for you yet and thanks for reporting!

**Comment by locks** [comment]
@happydude are you on the Ember Discord server? I'd like to ask you some questions related to this.
