### ISSUE TITLE
[redesign] Navbar opens behind leaflet map on /community/meetups page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#569]
I'm not sure if this is an issue for the website or the styleguide i.e. if we should be attempting to lower the z-index of the leaflet map on the website or increasing the z-index of the navbar in the styleguide :thinking:

**Comment by Windvis** [comment]
I would simply add a new z-index to the map wrapper to give it a local stacking context. It feels weird to update the style guide z-index system simply because an addon uses certain z-index values.

**Comment by mansona** [comment]
@Windvis yes that is my thought as well 👍

**Comment by mansona** [comment]
Fixed in #574
