### ISSUE TITLE
browser/device review

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#570]
To prep for initial launch, the website should be given a basic review in different browsers and on various devices.

## Helping out
If you decide to help out with this list, please visit our [Preview Site](https://deploy-preview-361--ember-website.netlify.com/) on one of the combinations listed in the "browsers and devices" list, and check for the three things listed in the "what to look for" list. Then, reply to this issue with your findings. 

## What to look for
Sites don't have to look exactly the same in every browser. But there are basic things that we're checking for: 
1. does anything look obviously out of place? 
2. are you able to keyboard navigate through the page by using the `TAB` key?
3. is there any part of the page that simply isn't rendering, or do you see an error in the console log that you don't see when you are checking the site on other browsers/platforms?

## Browsers & Devices
List of browsers/devices to use:
- [x] Chrome, MacOS
- [x] Firefox, MacOS
- [x] Safari, MacOS
- [x] Edge, MacOS
- [x] Chrome, Windows
- [x] Firefox, Windows
- [x] Edge, Windows
- [x] IE11, Windows
- [x] iPhone
- [ ] Android

**Comment by Windvis** [comment]
Is IE11 support still needed? I assume most of the people checking the ember website are using an evergreen browser, or am I wrong?

**Comment by mansona** [comment]
@Windvis well another way to look at it is that Ember supports IE11 so that means it is 100% required 😂 

As @MelSumner says in the issue `Sites don't have to look exactly the same in every browser.` so that means we can have some fallback styles that look OK but not super slick, but it can't be **broken** in IE11 or a **bad** experience

**Comment by Windvis** [comment]
I don't think that the support of the framework should decide the support of the website. I don't know the numbers but it feels like a waste to polyfill / transpile code for users that will never visit the website.

But if that's the policy for the official Ember websites :smile:.

**Comment by MelSumner** [comment]
@Windvis we have to because we have a lot of enterprise users, and they don't get to choose the browser they use at work.

**Comment by Windvis** [comment]
@MelSumner I can't believe those enterprise users will visit the ember website. The target audience of the ember website are primarily web developers right? I can imagine that management types also check the website to see if it's a viable technology, but I would think that even those are more tech savvy people who use modern browsers. All of this is based on my gut feeling, of course 😄 , I don't have numbers to back up my statements. Do we have browser usage statistics from the current website?

Also, are you sure the IE11 requirement was ever enforced before? I opened the current (non-redesign) version in IE11 and that doesn't work either.

Anyway, if IE support _is_ required for the redesign I think it shouldn't be a blocker for release. I don't think the current implementation was ever tested in IE11 so it will probably require some work.

**Comment by kennethlarsen** [comment]
<img width="994" alt="Screenshot 2020-02-20 at 17 11 36" src="https://user-images.githubusercontent.com/1408595/74954869-12309e80-5404-11ea-89ec-056c9502468b.png">
Firefox on Mac

**Comment by MelSumner** [comment]
@Windvis I definitely know they do, and I definitely know it's a requirement. :) Thanks for the feedback though!

**Comment by MelSumner** [comment]
> Firefox on Mac

Thanks @kennethlarsen - issue filed here: https://github.com/ember-learn/ember-website/issues/590

**Comment by acorncom** [comment]
iPhone 8, right most tab kicks off the screen

![99D88BE4-C981-4B39-88DB-9878A8A3D86D](https://user-images.githubusercontent.com/802505/75008409-3062c280-5435-11ea-844c-e2f44e3faa0e.png)

**Comment by kennethlarsen** [comment]
Mac, Firefox:

The image slider slides a bit up and down as well on Firefox resulting in some unexpected scroll highjacking.

[See the bug in action](https://i.imgur.com/tIOBljt.gifv)

**Comment by mansona** [comment]
@MelSumner as this is the last issue left in the Website Redesign Project board I'm wondering what we want to do with it? 🤔 

I know there are still some issues with IE11 so I guess that we should keep it open for now, but maybe we can move it to In Progress on the phase 2 board or something? thoughts?
