### ISSUE TITLE
[Redesign] Blurry images on the Community page

### ISSUE THREAD

**Issue by Windvis** [ember-learn/ember-website#576]
I noticed the images are a bit blurry due to them being upscaled and that's especially noticeable on mobile devices. Are there any plans of them being replaced with SVG versions?

An alternative solution could be to not upscale them and just center the images on mobile, and left / right align them on larger devices (depending on how they are positioned next to the text).

Mobile screenshot:
![Screenshot_2020-02-17 Community - Ember js](https://user-images.githubusercontent.com/3533236/74674135-fed9c500-51b0-11ea-908a-f1760ac69afe.png)

**Comment by MelSumner** [comment]
I see what you mean- but they didn't used to be this way, so we might have to figure out what changed to make them this way. @mansona maybe this needs some troubleshooting, or do you already know what's caused this to happen?

**Comment by Windvis** [comment]
They all have the `.img-fluid` class applied to them. They didn't have something similar in the old design so they were never scaled up. It seems these classes were added in https://github.com/ember-learn/ember-website/pull/456 and the pixelated look was mentioned there as well :smile:.

**Comment by mansona** [comment]
@MelSumner the best way to fix this is to get higher res images for those (or replace them with SVGs) do we know if we have the original files?

**Comment by MelSumner** [comment]
@mansona - 
- remove .img-fluid class 
- make sure we have the height/width declared
- set that to the max height/width
- find the original files
- convert to svg or png
