### ISSUE TITLE
Ember Users list items display as boxes of different heights in Safari

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-website#582]
When looking over the latest deploy preview of the nifty new website, I noticed a non-blocking padding bug on the Ember Users page in Safari on my Mac that isn't visible in Chrome. Specifically, for a given "ember user" `<li>`, the specific height seems to adjust somewhat randomly to the point it's distracting as I wonder what height the next row might be:

<img width="1015" alt="Screen Shot 2020-02-17 at 9 52 00 PM" src="https://user-images.githubusercontent.com/802505/74705051-c4335500-51cf-11ea-8dcc-909a979547b3.png">

**Comment by mansona** [comment]
I'm pretty sure this is the bug that @pichfl has identified a few times related to Safari not playing well with images whose heights are defined by CSS 🤔 something about intrinsic sizes but I don't fully understand tbh 🙈

**Comment by pichfl** [comment]
It's a matter of interplay between the browsers flex box / grid layout calculations and the assumed image ratio. It seems Webkit does not trigger a second render pass when images are loaded inside a flex / grid layout. Adding width and height to `<img>` does ensure each image has a defined initial ratio even when no CSS is present and the image isn't loaded yet. This way, the browser can apply all layout calculations even before the image is fully loaded, making a second render pass unnecessary.

**Comment by pichfl** [comment]
To fix this in timely manner, I recommend using `class="well well-16/9"` on the wells to enforce a ratio on the wells.

**Comment by ddoria921** [comment]
Created a PR for this here https://github.com/ember-learn/ember-website/pull/586 based on @pichfl's recommendation and it fixed the issue in Safari

**Comment by mansona** [comment]
Fixed in #586
