### ISSUE TITLE
[Question] Should Ember's website "Ecosystem" header talk about "ember-data" as well?

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#584]
The "Ecosystem" content on https://emberjs.com/learn reads:

> One of the main strengths of Ember is how shared conventions enable developers to build on top of each other's work and improve the ecosystem for everyone. For example, here are some **projects closely maintained by Ember teams**

And it doesn't talk about `ember-data` in specific, though it is available in the previous section. 

Should we add `ember-data` as part of this list as well?

**Comment by abhilashlr** [comment]
Since this was related to the old ember website UI, closing this issue.

**Comment by amyrlam** [comment]
cool, thanks!
