### ISSUE TITLE
Double scroll bar on the photos section

### ISSUE THREAD

**Issue by ming-codes** [ember-learn/ember-website#600]
The inner scroll bar doesn't scroll anywhere but it can be sticky and interfere with outer scroll.

The bug is present in Safari but not in Chrome.

**Comment by cmitz** [comment]
Do you mean the image grid (in css as `homepage-image-grid`)?

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/5594436/75115979-31c60200-5664-11ea-8300-912d1e1082a4.png">

I have the same in Firefox

**Comment by ming-codes** [comment]
Yes, that’s it.

**Comment by mansona** [comment]
Fixed in #605
