### ISSUE TITLE
Improve color contrast ratio of survey banner

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#603]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/5667722/75098328-aeac9980-55da-11ea-9f4f-b49133f7b37e.png">

The accessibility score of the landing page is at 98! That's always awesome :)
Lighthouse just reported issues at 3 places w.r.t "Color contrast ratio".

Especially this contrast ratio report is on the top banner that says "Take the 2020 community survey".

**Comment by abhilashlr** [comment]
I believe this can be closed since the PR has been merged already 👍

**Comment by amyrlam** [comment]
@abhilashlr thanks!
