### ISSUE TITLE
Add Ember Times to the homepage somewhere

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#609]
We currently have a section for "unofficial community resources" on the homepage but we don't have anywhere to put general **official** resources that we want to highlight. 

Even if we don't want a general "list of official resources" the Ember Times is important enough that we should give it somewhere pride-of-place on the homepage to inform people about it and encourage them to subscribe 👍

**Comment by alexeykostevich** [comment]
@mansona , this is a great idea — Ember Times is definitely worth to be noticed!

Let me share some my thoughts. I apologise if some don’t make much sense: I’m totally new to Ember and, likely, don’t see the whole picture. However, a fresh look from newcomers can still be helpful :)

Looking at http://emberjs.com, I’ve found out a few things, which might me important:
- There is no real separation between official and community resources on the website. For example, the [Community](https://emberjs.com/community) page mentions the Blog, Ember Times, Ember Weekly in the “Stay Up to Date with the Latest News” section.
- Ember Times issues are published both in the [Blog](https://blog.emberjs.com/) and on the [Ember Times](https://the-emberjs-times.ongoodbits.com/) website. Interestingly, I was not aware about a dedicated website for Ember Times and just checked the Blog.

Taking this into account, I would recommend 2 possible ways forward:
1. If the Ember Times website is not going to be deprecated in favour of the Blog, we can replace the “Blog” menu in the header with more high-level “News”. “News” will include “Blog”, “Ember Times” and “Ember Weekly” (this is what https://vuejs.org/ does). This being the case, I would also consider publishing issues only in Ember Times (lbut not the Blog to keep their purpose well-defined.
2. If the Ember Times website is going to be deprecated in favour of the Blog, I would keep the menu as is. Then, we can provide a way to subscribe to all blog updates right in the Blog.

With regards to me, I like option 1: Ember Times has charm of a newspaper :) However, it will require additional effort to maintain 2 separate websites.

With regards to encouraging people to subscribe, we could create a banner (with a mascot-reporter?) as a reusable [ember-styleguide](https://github.com/ember-learn/ember-styleguide) component and add it to the [Home](https://emberjs.com/) and [Blog](https://blog.emberjs.com/) pages.

**Comment by amyrlam** [comment]
Made a PR to kick off some discussion on implementation: https://github.com/ember-learn/ember-website/pull/662

**Comment by manurampandit** [comment]
@mansona - As the [PR ](https://github.com/ember-learn/ember-website/pull/662) by @amyrlam is merged for this, can we mark this as closed (or move forward the discussion if required)

**Comment by amyrlam** [comment]
@manurampandit @mansona I'll close this since it's there now: 

![image](https://user-images.githubusercontent.com/1372946/101230285-38ed5800-3659-11eb-8dae-be3616945256.png)

**Comment by manurampandit** [comment]
Thanks a lot @amyrlam for closing this.
