### ISSUE TITLE
Update LTS Channel page

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#617]
Currently the LTS schedule shows too many End Of Life (EOF)versions. It should be updated to show only the current active LTS plus the previous LTS. Currently this is 3.16, 3.12, and 3.8.

After the LTS support schedule table, past LTS versions should be listed, possibly with the date when they were EOF. Example:

```
These last LTS versions are no longer maintained: 2.4 (Nov 2016), 2.8 (April 2017), ….
```

**Comment by mansona** [comment]
I think this is a great idea @locks 🎉 is there any discussion needed for this or can we just go ahead do you think?

**Comment by locks** [comment]
This was the outcome of a discussion last team meeting, so we should be good to go!
https://github.com/emberjs/core-notes/blob/master/learning-team/2020-03/2020-03-05.md
