### ISSUE TITLE
[BUG] Fix spacing in LTS page

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#633]
The listing of past LTS editions that follows the table does not have adequate spacing:

![image](https://user-images.githubusercontent.com/32344/78262714-e15e8180-74f8-11ea-82b1-eb2d01679120.png)

**Comment by alexeykostevich** [comment]
@locks , could I take this issue?

This table lives on the [LTS - Releases - Ember.js](https://emberjs.com/releases/lts) page.

From what I see, the table has been migrated from the legacy [builds](https://github.com/ember-learn/builds) app in https://github.com/ember-learn/ember-website/commit/32eabcb2daf006596ee401f7d6fd0f46b72fa037.

The *builds* app used the following CSS to style this table:
https://github.com/ember-learn/builds/blob/3b5bd34844a747ff39308c434043b45ca71fe23e/app/styles/app.css#L3

However, these styles have not been migrated. So,  after some time, the `lts-schedule table` classes have been removed from HTML in https://github.com/ember-learn/ember-website/commit/534a99b4aa01bc9d7cf72da10e583da2bc1ee7c8 (likely, as unused).

Taking into account, that [ember-styleguide](https://github.com/ember-learn/ember-styleguide) does not provide common styles for tables so far, would it be the right direction to add the `lts-schedule` class again and migrate its styles from the *builds* app?

**Comment by mansona** [comment]
@alexeykostevich it's probably a good idea for us to consider default table styles for the styleguide 🤔 

@pichfl what do you think?

**Comment by alexeykostevich** [comment]
Sounds good! I would be glad to help with implementing a new ember-styleguide component (either pure CSS or Ember one) when we have an agreement on the design.

**Comment by pichfl** [comment]
Putting it on my list of todos.
