### ISSUE TITLE
Confirm timings in LTS schedule

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#634]
Recently the releases page for the [LTS channel](https://emberjs.com/releases/lts/) was updated to account for 3.16. I would like the core teams to triple check that the math is correct.

**Comment by rwjblue** [comment]
The general verbiage seems correct, but the specific dates seem off by a cycle.

Specifically, I would expect to see:

* 3.16 gets bugfixes until 2020-11-12 (36 weeks from when 3.16 was promoted to LTS, aka 2020-03-05)
* 3.16 gets security fixes until 2021-03-18 (54 weeks from when 3.16 was promoted to LTS)
* 3.12 gets bugfixes until 2020-05-28 (36 weeks from when 3.12 was promoted to LTS)
* 3.12 gets security fixes until 2020-10-01 (54 weeks from when 3.12 was promoted to LTS)

**Comment by rwjblue** [comment]
@ijlee2 - Does my summary make sense? Can we document this somewhere (to make it easier for the next LTS release update)?

**Comment by ijlee2** [comment]
Thanks, @locks and @rwjblue . Let me take a look later in the evening and get back to you.

**Comment by ijlee2** [comment]
@rwjblue I read your explanation and checked that I could add 36 and 54 weeks from 3.13.0 or 3.17.0 release date to arrive at the dates that you had provided. Thanks!

I think documenting would be a good solution.

When I had worked on #627, I had wondered if we could create a template helper that would add `x` number of weeks.

Currently, the table shows,

<img width="480" alt="Screen Shot 2020-04-02 at 5 27 20 PM" src="https://user-images.githubusercontent.com/16869656/78305740-4c16b980-7507-11ea-9a9f-f7b696c7203b.png">

In the 2nd column, if we instead show the LTS promotion dates, we could use the helper to derive the dates for the 3rd and 4th columns.

**Comment by locks** [comment]
I used `date-fns` to build a little release calendar schedule for myself, you can check it out https://glitch.com/edit/#!/emberjs-release-calendar?path=app/controllers/application.js:4:21.

**Comment by ijlee2** [comment]
@locks Thanks!

When I clicked on the link, I saw a message that no project was found. Is it, by any chance, not public?

**Comment by locks** [comment]
I thought it was a public link 😅. Here's the relevant code:

```
import { addWeeks, startOfWeek, setDate, setMonth, setYear } from "date-fns";

function newDate(year, month, day) {
  let date = new Date();
  
  console.log("DATE", date, setMonth(date, month));
  
  return setYear(
    setMonth(
      setDate(
        date,
        day),
      month),
    year);
}

const releases = [{
  version: "3.6",
  date: newDate(2018, 11, 13)
}, {
  version: "3.7",
  date: newDate(2019, 0, 7)
}];

for (let i = 8; i <= 20; i++) {
  releases.push({
    version: `3.${i}`,
    date: addWeeks(
      startOfWeek(releases[releases.length - 1].date, { weekStartsOn: 1 }),
      6
    )
  });
}
```

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-learn/ember-website/pull/635
