### ISSUE TITLE
Add markdown linting?

### ISSUE THREAD

**Issue by maxwondercorn** [ember-learn/ember-website#640]
Do we want to add the markdown linting setup that's used in the guides?  Content probably won't change a lot but we want to make sure we're presenting our best face

**Comment by mansona** [comment]
I don't think that there is much need for **markdown** linting in this project 🤔 as most of the content that is in Markdown is more like data rather than the bulk of the content on any of the pages.

If the reason you are proposing it is to make sure that alex is run and spellcheck is run on the main content, then we would need to investigate something that would run on the output html rather than the input Markdown. Does that make sense?

**Comment by maxwondercorn** [comment]
@mansona Yes, I saw the markdown and thought the new website was generated similar to the guides. I think there is always a need to verify spellchecking and other potential issues (ie. alex) on websites.  

There are a lot of eyes on the Ember website so it's likely issues will be caught but it's always nice to reduce cognitive load!

I've never done this myself by but `alex` can be run on html with the `--html` flag and I think `Remark` which is used in the markdown spell checking can also be used for html.  I'd have to research the Remark part if there is an interest

**Comment by MelSumner** [comment]
@maxwondercorn I use a markdown linter locally and it helps, I also don't mind a linter being added to the project. You're right that it reduces cognitive load! Do you have a PR in that adds a markdown linter in particular?

**Comment by maxwondercorn** [comment]
@MelSumner no I don’t have a PR but I can put one together this weekend

**Comment by abhilashlr** [comment]
@MelSumner @maxwondercorn I've tried markdown-lint for one of my ember projects using markdown. I can send in a PR quickly if no one has already begun work on this yet.

**Comment by mansona** [comment]
@abhilashlr @maxwondercorn  did you see my comment above? I don't think that adding markdown linting will give us much value for this project because most of our content is not in Markdown 🤔

**Comment by maxwondercorn** [comment]
@mansona @abhilashlr @MelSumner I wasn't looking at doing markdown linting per your earlier comments. We'd just copy what's done in the guides for that. I was looking at somehow linting the rendered website.

Since we are using Fastboot and `broccoli-static-site-json` I'm not sure it possible but I take that as a problem to solve.  Probably won't be a PR anytime soon...

**Comment by MelSumner** [comment]
@mansona yes but some of it is, and the consistency is nice. 👍

**Comment by MelSumner** [comment]
It seems like we don't have consensus on this so I'm going to go ahead and close the issue. Please do check out the markdown linter extensions available for IDEs like Visual Studio Code, though. Thank you!
