### ISSUE TITLE
Colocate components

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#707]
## Background

Over the next month or so, we want to upgrade `ember-source` to the latest (`v3.24` at the time of writing) and ensure that the app follows latest practices in Ember Octane.

## Description

In #706, I added default rendering tests for all components. Now that we have tests, let's move the template files so that we follow the default Octane project layout ([flat](https://github.com/ember-codemods/ember-component-template-colocation-migrator#flat-component-structure)).

## TODOs

Please make 2 commits for your pull request (one commit after completing each TODO item).

- [ ] Run [ember-component-template-colocation-migrator](https://github.com/ember-codemods/ember-component-template-colocation-migrator) to move template files in `app/templates` to `app/components`.
- [ ] Use `mv` command to manually un-pod `<EmberCliUsage>`, `<ProjectListing>`, `<ProjectListing::Beta>`, and `<RemoveSpinner>` components.

## References

- https://github.com/ember-codemods/ember-component-template-colocation-migrator
- https://cli.emberjs.com/release/advanced-use/project-layouts/

**Comment by bertdeblock** [comment]
@ijlee2 Maybe useful to add whether a **flat** or **nested** colocation structure is preferred?

**Comment by ijlee2** [comment]
@bertdeblock Thanks for the suggestion for clarification. I was thinking of [flat](https://github.com/ember-codemods/ember-component-template-colocation-migrator#flat-component-structure) since it is the default in a new app. I've updated the issue's description. 🙂

**Comment by bertdeblock** [comment]
@ijlee2 You can assign me for this one as well.

**Comment by ijlee2** [comment]
@bertdeblock Will do, thank you!

I just merged a pull request of mine. Just in case, can you check that you have the latest code?
