### ISSUE TITLE
Title helper from ember-page-title has been deprecated

### ISSUE THREAD

**Issue by czikarito** [ember-learn/ember-website#711]
Since v5.2.2 version of `ember-page-title` the {{title}} helper has been deprecated, which leads to warnings in the console

WARNING MESSAGE:
Using `{{title}}` helper is deprecated, use `{{page-title}}` instead.

![image](https://user-images.githubusercontent.com/15904756/104223482-f97a0e80-5443-11eb-9fff-16afa683d8ff.png)

**Comment by ijlee2** [comment]
@czikarito Thanks! It was on my to-do list for writing up issues.

Can you help me update the helpers to `{{page-title}}`? I can update the issue description to describe what else needs to be done to upgrade `ember-page-title` to the latest version.

Before we make changes, let me first add tests and ensure that every page has a title beforehand. Not every page has a unique title right now.

**Comment by czikarito** [comment]
@ijlee2 sure I can do it

**Comment by ijlee2** [comment]
Awesome, I'll let you know once the tests for page title are merged.

**Comment by ijlee2** [comment]
@czikarito I just merged #713, which checks the page title for most of the routes. For your pull request, can you:

1. Replace `{{title}}` helpers with `{{page-title}}` helper
2. Remove `<title>` element from `app/templates/head.hbs`
3. Run `yarn upgrade ember-page-title --latest` to install `v6` of the addon

Note, the pull request does not involve adding or updating the page title. We can do this in a separate issue and pull request if needed.

I haven't had to fix deprecation warnings for `ember-page-title v6` before, so I'm not sure if the 3 steps above are the right ones to take. You can try running `yarn test` after each step, in addition to running the app locally.

If you have suggestions for how we can upgrade `ember-page-title`, feel free to let us know!
