### ISSUE TITLE
Link to New Ember Job Board

### ISSUE THREAD

**Issue by wifelette** [ember-learn/ember-website#754]
**Is your feature request related to a problem? Please describe.**
We've nixed the Ember Job Board since there's a community member willing to manage it now, yay! The new site is https://emberwork.com/, and we'd like to link to it.

**Describe the solution you'd like**
As the job board has agreed to remain free, I'd like to add a link to it to some appropriate location on the site. This is both because our audience wants jobs, and because we like helping promote non-profit community efforts.

@mansona had ideas about where on the Community page to put it. Somewhere in that section seems great, though some additional prose will likely be needed since we don't have anything like it listed just yet.

**Describe alternatives you've considered**
We previously had our own job board, but ran out of bandwidth to maintain it. So we _had_ an alternative, and it was great, but we don't anymore, so this is a replacement. I'm in touch with the folks behind it on Discord if I can help with any questions we have for _them_.

**Comment by claeusdev** [comment]
@wifelette @mansona I would like to take this one if the ideas about where to put the link are finalized.

**Comment by wifelette** [comment]
Hi @claeusdev—looks like @herzzanu got to it first and didn't notice your comment, apologies! Hope you found something else to jump in on, we're grateful for any and all help <3

**Comment by claeusdev** [comment]
@wifelette hah, just saw it as well. I will definitely find something else to jump on
