### ISSUE TITLE
Add a permanent survey landing page

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#765]
We should have a landing page for the survey.

- /survey should be a top-level route
- the survey result pages should be child routes

**Comment by herzzanu** [comment]
@MelSumner I'd be happy to help on this one, but I need some guidance. Do we have a design for the survey landing page?

**Comment by MelSumner** [comment]
Thank you! I will defer to @mansona because there might be an initial plan already. 

Eventually we will want to integrate the sub domain but I think we should at least get a page integrated into the website to properly categorize/organize the content.

**Comment by herzzanu** [comment]
Awesome, thanks. @mansona please don't hesitate to ping me on that :)

**Comment by jaredgalanis** [comment]
Since this looks like it has been addressed in principal, closing this and adding a note to the website redesign board about subdomain support.
