### ISSUE TITLE
Remove 3.16 from LTS on March 17

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#788]
## Description

Please update https://emberjs.com/releases/lts by:

- Removing 3.16 from the table of currently supported LTS's
- Listing 3.16 in the paragraph that follows the table, along with the last minor release's date for 3.16

Please also check if https://emberjs.com/releases/beta and https://emberjs.com/releases/release can be updated (i.e. if there have been a new 3.26 beta and a new 3.25 minor release).

## Notes

The data for release dates can be found in:

- https://github.com/ember-learn/ember-website/blob/master/app/controllers/releases/lts.js
- https://github.com/ember-learn/ember-website/tree/master/data/project
- https://libraries.io/npm/ember-source

**Comment by fozy81** [comment]
Hi @ijlee2, I've taken a quick look at this issue. I noticed Ember has just rolled out [3.26 stable and 3.27 beta](https://libraries.io/npm/ember-source). So I've just updated the LTS and assume stable and beta version will be updated shortly as part of their release process?

**Comment by ijlee2** [comment]
Good question. Yep, let's only update the LTS page. We can update stable and beta pages once 3.26 is announced on the Ember Blog.

**Comment by fozy81** [comment]
Great, thanks for the help :+1: . PR ready for review.
