### ISSUE TITLE
Add link to "Ember Data" on home page?

### ISSUE THREAD

**Issue by bertdeblock** [ember-learn/ember-website#790]
Here:
<img width="295" alt="Screenshot 2021-03-06 at 18 42 30" src="https://user-images.githubusercontent.com/7403183/110215759-bec4ad80-7eab-11eb-9135-3bbd9d9097a9.png">

Could be a link to the repo or a link to the `Ember Data` section in the guides?

**Comment by ijlee2** [comment]
I think it's a good idea to add the link in the homepage so that people can learn more about Ember Data. I think https://guides.emberjs.com/release/models/ is better than `ember-data` repo.
