### ISSUE TITLE
2021 Contributors' Workshop: Create SplineChart class

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#826]
## Background

Until recently, the controller files for `ember-community-survey` pages included hundreds of hard-coded configuration objects for Highcharts. These objects were large and only worked with Highcharts. As a result, the objects were difficult to review quickly and posed a technical risk in maintenance.

To solve these issues, I have been writing classes that abstract creating a configuration object. These classes accept a minimal set of arguments so that we can better adapt to a breaking change in a Highcharts release or a migration to another chart library when needed.

## Description

First, please have a look at #784 and #778 (their first 4 commits), to see how I had created a class and wrote unit tests in a step-by-step manner.

To complete the issue, please create a class called `SplineChart` in `app/utils/highcharts` folder. The `SplineChart` class can be used to create configuration objects for chart type of `'spline'` in `ember-community-survey-2017` and `ember-community-survey-2018`.

Don't forget to write unit tests for `SplineChart`. 🙂

## Notes

The class is to adhere to the API of other, similar classes in this folder. In other words, the class accepts an object with 2 properties called `chart` and `rawData`. As output, the `highchartsOptions` returns the configuration object for rendering a spline chart.

To limit the scope of work and PR review, I recommend applying the `SplineChart` class to replace existing configuration objects in a separate issue and pull request.

**Comment by ijlee2** [comment]
Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.

**Comment by mamiller93** [comment]
I can try this!

**Comment by ijlee2** [comment]
@mamiller93 Great, thank you for your help! If you have any questions, please feel free to let me know on Discord. You can find me with `@ijlee2`.
