### ISSUE TITLE
2021 Contributors' Workshop: Address 2 accessibility issues in /editions/octane

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#827]
## Description

In this issue, we will fix 2 accessibility issues in `editions.octane` route template. The 2 issues have been [pointed out by our application test](https://github.com/ember-learn/ember-website/blob/b2af864c7704200e1beda0e9866d6650ea50bbd8/tests/acceptance/editions/octane-test.js#L28-L37).

### 1. aria-valid-attr-value

Reference: https://dequeuniversity.com/rules/axe/4.1/aria-valid-attr-value

The problem occurred because we used the `aria-labelledby="octane-edition"` in `app/templates/editions/octane.hbs`, but there is no HTML element with the ID `octane-edition`. To fix the issue, you can assign the ID `octane-edition` to the `<h1>` element.

Please check that the issue has been fixed by removing the `aria-valid-attr-value` exception in the application test.

```javascript
// Before
await a11yAudit({
  rules: {
    'aria-valid-attr-value': {
      enabled: false,
    },
    'heading-order': {
      enabled: false,
    },
  },
});

// After
await a11yAudit({
  rules: {
    'heading-order': {
      enabled: false,
    },
  },
});
```

Afterwards, create and push a commit.

### 2. heading-order

Reference: https://dequeuniversity.com/rules/axe/4.1/heading-order

The problem occurred because the `<EsLinkCard>` component, which comes from [ember-styleguide](https://github.com/ember-learn/ember-styleguide/blob/master/addon/templates/components/es-link-card.hbs), hard-coded an `<h3>` element. There was no `<h2>` element prior to the component's appearance.

Currently, in production, we see 5 cards that have a basic appearance:

<img width="800" alt="five_cards" src="https://user-images.githubusercontent.com/16869656/112848093-fdfbae00-90a7-11eb-8d22-a586d0d7b5fb.png">

Let's use a proper list, i.e. `<ul>`-`<li>` combination, instead:

```handlebars
{{!-- Before --}}
<ul class="unstyled-list grid lg:grid-5">
  <EsLinkCard @href="https://blog.emberjs.com/2019/12/20/octane-is-here.html" @title="Read the announcement" />
  <EsLinkCard @href="https://guides.emberjs.com/release/getting-started/quick-start/" @title="Try the new app Quick Start" />
  <EsLinkCard @href="https://guides.emberjs.com/release/tutorial/" @title="Follow the Tutorial" />
  <EsLinkCard @href="https://guides.emberjs.com/release/" @title="Read the Guides" />
  <EsLinkCard @href="https://guides.emberjs.com/release/upgrading/current-edition" @title="Learn how to upgrade" />
</ul>

{{!-- After --}}
<ul>
  <li>
    <a
      href="https://blog.emberjs.com/2019/12/20/octane-is-here.html"
      rel="noopener noreferrer"
      target="_blank"
    >
      Read the announcement
    </a>
    ...
  </li>
</ul>
```

The list above can be styled so that it looks similar to the list below (found in the same page):

<img width="800" alt="list" src="https://user-images.githubusercontent.com/16869656/112848478-66e32600-90a8-11eb-96b8-99d69a146af8.png">

Please check that the heading issue has been fixed by removing the `heading-order` exception in the application test.

```javascript
// Before
await a11yAudit({
  rules: {
    'heading-order': {
      enabled: false,
    },
  },
});

// After
await a11yAudit();
```

Afterwards, create and push a commit.

**Comment by ijlee2** [comment]
@Krashaune Great, thank you for your help! If you have any questions, please feel free to let me know on Discord. You can find me with `@ijlee2`.

**Comment by broxsonl** [comment]
For documentation, @Krashaune and I are pairing on this. :)
