### ISSUE TITLE
2021 Contributors' Workshop: Address 2 accessibility issues in /sponsors

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#828]
## Description

In this issue, we will fix 2 accessibility issues in `sponsors` route template. The 2 issues have been [pointed out by our application test](https://github.com/ember-learn/ember-website/blob/b2af864c7704200e1beda0e9866d6650ea50bbd8/tests/acceptance/sponsors-test.js#L28-L37).

### 1. list

Reference: https://dequeuniversity.com/rules/axe/4.1/list

The problem occurred because we added a `<figure>` element directly inside a `<ul>` element. To fix the issue, please surround the `<figure>` tag with `<li>`.

Please check that the issue has been fixed by removing the `link` exception in the application test.

```javascript
// Before
await a11yAudit({
  rules: {
    'link-name': {
      enabled: false,
    },
    list: {
      enabled: false,
    },
  },
});

// After
await a11yAudit({
  rules: {
    'link-name': {
      enabled: false,
    },
  },
});
```

Afterwards, create and push a commit.

### 2. link-name

Reference: https://dequeuniversity.com/rules/axe/4.1/link-name

The problem occurred in the list of sponsors, because each `<a>` element does not have a discernible text.

One way to solve the issue is to provide an ARIA attribute (investigate, whether to the link or to the image) so that the attribute describes what the anchor is about. There may be another, better approach so please take some time to investigate, and ask for help in the `#topic-a11y` channel on Discord when needed.

Please check that the heading issue has been fixed by removing the `link-name` exception in the application test.

```javascript
// Before
await a11yAudit({
  rules: {
    'link-name': {
      enabled: false,
    },
  },
});

// After
await a11yAudit();
```

Afterwards, create and push a commit.

**Comment by MarissaWood** [comment]
I can help with this issue! This will be my first contribution 😊

**Comment by ijlee2** [comment]
@MarissaWood Great, thank you for your help! First time contributors are always welcome in the Ember community.

If you have any questions, please feel free to let me know on Discord. You can find me with `@ijlee2`!
