### ISSUE TITLE
Request for linters to be setup for the project

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#83]
We need to setup linters like template-lint, scss-lint and eslint for the project

**Comment by aklkv** [comment]
I have PR ready with ember-cli upgrade, I will add this as part of this PR. Might not bee scss-lint tho. This can go as a separate thing.

**Comment by mansona** [comment]
@aklkv if you can do the same thing that you did with styleguide and "stage" the PRs that would be very useful so that the the PRs are easier to merge 👍

**Comment by aklkv** [comment]
@mansona I think this is fixed now with #86, #88, #87
