### ISSUE TITLE
Remove unused Highcharts code (Part 1)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#845]
## Background

Until recently, all Highcharts objects were manually configured, then _merged_ with a default configuration object. 

Now that configuration objects are created as an instance of a chart class, we can remove code that had been based on the prior approach.

## Description

We'll remove unused code in a few steps (parts). The goal of the 1st step is to **simplify the API of `<Highcharts>` component**.

### 1. Current approach

Once we create an instance of a chart class, we have to pass the instance's `options` and `data` properties separately. This architectural approach allowed backwards compatibility.

As an illustration, in an `ember-community-survey` controller, suppose that we have `chartHowLong`:

```javascript
const chartHowlong = new VerticalBarChart( ... ).highchartsOptions;
```

Note that `chartHowlong` is an **instance property** of the `VerticalBarChart` class.

In the corresponding route template, we would write,

```handlebars
<Highcharts
  @chartOptions={{this.chartHowlong.options}}
  @data={{this.chartHowlong.data}}
/>
```

### 2. New approach

Recall that the goal of this issue is to simplify the API of the `<Highcharts>` component.

#### Step 1

Wherever the component is invoked (in the `ember-community-survey` controllers), we want to pass just 1 argument, called `@chart`:

```handlebars
{{!-- Before --}}
<Highcharts
  @chartOptions={{this.chartHowlong.options}}
  @data={{this.chartHowlong.data}}
/>

{{!-- After --}}
<Highcharts
  @chart={{this.chartHowlong}}
/>
```

To make a minimal change to the component's class, please update only the getter `chartOptions`.

https://github.com/ember-learn/ember-website/blob/19b5e447f7465757dfd6c84fcbe1ab69f1caaefd/app/components/highcharts.js#L18-L22

Afterwards, please check that all tests pass. (You may need to update some tests.)

#### Step 2

Next, we will redefine `chartHowlong`. Before, it represented an instance property of a chart. Now, it will represent the instance itself (the "whole object," if you will):

```javascript
// Before
const chartHowlong = new VerticalBarChart( ... ).highchartsOptions;

// After
const chartHowlong = new VerticalBarChart( ... );
```

Note that we want to redefine `chartHowLong` so that the following template code makes sense:

```handlebars
<Highcharts
  @chart={{this.chartHowlong}}
/>
```

That is, both left-hand side (`@chart`) and right-hand side (`this.chartHowlong`) represent a chart.

Once again, you will need to update the getter `chartOptions` in `<Highcharts>`'s component class. Please check that all tests pass.

**Comment by ijlee2** [comment]
@srih4ri Can I get your help with this issue? I think it may help with understanding component arguments (designing a component).

**Comment by srih4ri** [comment]
> @srih4ri Can I get your help with this issue? I think it may help with understanding component arguments (designing a component).
Sure!
