### ISSUE TITLE
[BUG] Filtering in /mascots is not working

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#862]
**Describe the bug**

When a user visits https://emberjs.com/mascots, then clicks on one of the filters (e.g. `Meetups`), the user does not see _any_ Meetup-related mascots.

I think a URL malformation is the issue. For some reason, the query parameter `filter` includes a space `%2F` at the end, e.g. `https://emberjs.com/mascots?filter=meetup%2F/`.

When the user clicks on `Meetups`, then on `Small`, we can see `%2F%2F` (i.e. more than one of `%2F`).

We do have application tests that check for the query parameter. In short, how the URL is formed may be different between production and testing.

- [A user can filter mascots](https://github.com/ember-learn/ember-website/blob/main/tests/acceptance/mascots-test.js#L51-L63)
- [A user can change the size of mascots](https://github.com/ember-learn/ember-website/blob/main/tests/acceptance/mascots-test.js#L95-L108)

**Expected behavior**

When the user clicks on a filter, the Mascots page will be able to limit which mascots are shown to the user.

When the user refreshes the page (with the `filter` query parameter on), the Mascots page will be able to limit which mascots are shown to the user.

**Recording**

![recording](https://user-images.githubusercontent.com/16869656/129674533-6e0b7704-c7be-45fa-9ee2-bdbe91621012.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 92.0.4515.131

**Comment by claeusdev** [comment]
if nobody has claimed this i would like to @ijlee2

**Comment by mansona** [comment]
Sorry this is as a result of the thing we need to add the trailing slash to the end of the url: https://github.com/ember-learn/ember-website/blob/main/app/locations/trailing-history.js

It seems like I didn't correctly support query parameters in my implementation 🤔

**Comment by ijlee2** [comment]
Hi, @claeusdev. Thank you for volunteering to help. I'll go ahead and assign the issue to you.

@rajakvk: To confirm, were you looking into solving the issue as well?
