### ISSUE TITLE
Update banners for site

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#906]
A few notes, for the banners- this might need to be broken out into separate issues, but for now I'm just trying to capture thoughts since we shipped a PR yesterday (it was the correct thing to do but the outcome still needs work). 

-  [x] On March 1, move the link to the BLM page to a link in the nav, in the community section
-  [ ] Update the banner component so that we can have one banner with multiple items, not stacked banners. 
-  [x] change the banner text from "Invasion of Ukraine" to "Support the people of Ukraine" (and consider removing the flag emoji)

Also for the Ukraine page prose: 
- [x] it needs to be re-checked for grammar and accuracy. 
- [x] Update some of the more inflammatory prose, such as changing the references to "Russia" changed to "the Russian military" or "the Russian government"
- [x] ensure that all links go to verified charities
- [x] encourage community members that live in countries with a democratic process to contact their representatives

**Comment by MelSumner** [comment]
PR #909 should resolve a bunch of these items

**Comment by MinThaMie** [comment]
@MelSumner I feel that #925 fixed the last point of multiple items :) Thanks to @jeffdaley
