### ISSUE TITLE
Add updated EmberConf CTA

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-website#907]
Update the CTA for EmberConf and add that back in to the home page.

**Comment by MelSumner** [comment]
@mansona @locks is this something either of you can do, or do we need @wifelette to handle getting the graphic updated?

**Comment by wifelette** [comment]
Adding @jeffdaley who is working on EmberConf design stuff this week :)

**Comment by jeffdaley** [comment]
I'll hop on this tomorrow morning
