### ISSUE TITLE
Title says "EmberWebsite" for the project

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#93]
This needs to be dynamic based on the page rather than a static one.

**Comment by locks** [comment]
@mansona it's merged

**Comment by mansona** [comment]
This issue is now done because it no longer says "EmberWebsite" as the title. 

As for the question of dynamically changing the title, I think it's best that we continue that conversation over here: https://github.com/ember-learn/ember-website/issues/313
