### ISSUE TITLE
Update links in navbar to use internal links

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-website#97]
Since this app was initially setup, we've landed a bunch of pages from the ember website. We'll need to update the [nav bar links](https://github.com/ember-learn/ember-website/blob/master/app/links.js) to point to the routes configured in this app so that whenever we launch preview apps & navigate via the navbar we end up landing on a page within this app instead of being redirected to emberjs.com

**Comment by abhilashlr** [comment]
@sivakumar-kailasam I believe this would require changes in ember-styleguide as well.? Please correct me if I am wrong.

**Comment by sivakumar-kailasam** [comment]
No the updates are on https://github.com/ember-learn/ember-website/blob/master/app/links.js.

**Comment by sivakumar-kailasam** [comment]
If the links are configured as a relative path, then we wouldn't any changes to `ember-styleguide`. Do correct me if I'm wrong about that 😅

**Comment by abhilashlr** [comment]
I thought it was about using `link-to`. Perhaps, using a relative path to `<a>` will work but there will be page load that happens instead of a smooth transition. This would result in the assets being re-fetched.

**Comment by sivakumar-kailasam** [comment]
Ah yes, my bad 😅

**Comment by mansona** [comment]
We might not need to add anything to styleguide on this one folks 🤔 I think just adding ember-href-to will catch any transitions and do the right thing as long as they are "path only links" as in `/team` instead of `https://emberjs.com/team`

**Comment by j-brennan** [comment]
@mansona I had a chat with you recently about this issue - and we believe it to be resolved.

**Comment by mansona** [comment]
thanks @j-brennan 👍 yes this issue is in fact fixed 🎉
